[RF ET][REG CTRL][S5308AP] CLK_Gating :: rat(%d), tx path(%d), onoff(%d)
[RF ET][REG CTRL][S5308AP] CLK_Gating :: Check RAT - rat (%d)
[RF ET][REG CTRL][S5308AP] DPD :: rat(%d), tx path(%d), lut_num(%d)
[RF ET][REG CTRL][S5308AP] DPD :: rat(%d), tx path(%d), tab_num (%d) lut_num(%d)
[RF ET][REG CTRL][S5308AP] SF :: rat(%d), tx path(%d), lut_num(%d)
[RF ET][REG CTRL][S5308AP] GainTable :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP] LUT_Sel :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP] Delay :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP] ET_DAC :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP] ET DAC :: on_off (%d), et_dac_mode_val (0x%x), et_ctrl (0x%x)
[RF ET][REG CTRL][S5308AP] ET_IN_DATA_SEL :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP] ET_DAC_IN_GAIN :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP] IFFT_GAIN :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP] IFFT_GAIN :: ifft_slot0 (0x%x), ifft_slot1 (0x%x)
[RF ET][REG CTRL][S5308AP] Tx_4G_MOD_GAIN_Set_ET_IFFT_Gain CC Info Error : err (0x%x), tx_path info (%d)
[RF ET][REG CTRL][S5308AP] Tx_4G_MOD_GAIN_Read_ET_IFFT_Gain CC Info Error : err (0x%x), tx_path info (%d)
[RF ET][REG CTRL][S5308AP] DGC_GAIN :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP] DGC_GAIN :: dgc_gain0 (0x%x), dgc_gain1 (0x%x)
[RF ET][REG CTRL][S5308AP] TxF_Filter_Set_ET_DGC_Gain CC Info Error : err (0x%x), tx_path info (%d)
[RF ET][REG CTRL][S5308AP] TxF_Filter_Read_ET_DGC_Gain CC Info Error : err (0x%x), tx_path info (%d)
[RF ET][REG CTRL][S5308AP] Main_Path_Block :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP] ET_Path_Block :: rat(%d), tx path(%d), bw(%d)
[RF ET][REG CTRL][S5308AP] Generate_1tone :: rat(%d), tx path(%d), on_off(%d)
[RF ET][REG CTRL][S5308AP] RF_Modem_ET_TxF_Filter_Generate_1tone :: Invlid SPL rate(%d)
[RF ET][REG CTRL][S5308AP] Not Allowed TX path [%d]
[RF ET][REG CTRL][S5308AP] Write_DPD_by_Tool :: rat(%d), tx path(%d), lut_num(%d)
[RF ET][REG CTRL][S5308AP] Write_SF_by_Tool :: rat(%d), tx path(%d), lut_num(%d)
[RF ET][REG CTRL][S5308AP] Read_DPD :: rat(%d), tx path(%d), lut_num(%d)
[RF ET][REG CTRL][S5308AP] Read_DPD :: rat(%d), tx path(%d), tab_num (%d) lut_num(%d)
[RF ET][REG CTRL][S5308AP] Read_SF :: rat(%d), tx path(%d), lut_num(%d)
[RF ET][REG CTRL][S5308AP] Get_Reg_Addr
[RF ET][REG CTRL][S5308AP] Get_Reg_Addr :: REG TYPE(%d) BASE(0x%x) ADDR(0x%x)
[ET ERROR][REG CTRL][S5308AP] Get_Reg_Addr :: Out of Range Error : Addr(0x%x) Range(0x%x ~ 0x%x)
[ET ERROR][REG CTRL][S5308AP] Get_Reg_Addr :: Get reg info index Error
[ET ERROR][REG CTRL][S5308AP] Get_Reg_Info_Index :: No Proper Register! reg_type(%d)
[RF ET][REG CTRL][S5308AP] Get_Reg_Info_Table
[RF ET][REG CTRL][S5308AP] Config_CFR :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP] Read_Swap_Status :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP] Set_FBRX_Cal_Mode :: rat(%d), tx path(%d), on_off(%d)
[RF ET][REG CTRL][S5308AP] Set_DAC_BW_setting :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP] IFFT_GAIN_SLO :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP] IFFT_GAIN_SLO :: ifft_gain_tx1 (0x%x), ifft_gain_tx2 (0x%x)
[RF ET][REG CTRL][S5308AP] IFFT_GAIN_SLO :: ifft_gain_tx1 (0x%x), ifft_gain_tx2 (0x%x)
[RF ET][REG CTRL][S5308AP] Get_Ctrl_Tx_Path_Info :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP] Get_Ctrl_Tx_Path_Info error (0x%x)
[RF ET][REG CTRL][S5308AP] DPD_Sum_Mode :: rat(%d), tx path(%d), on_off(%d)
[RF ET][REG CTRL][S5308AP] Get_Multi_Tab_DPD_LUT_Sel_Info :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP] SLO_UL_DMixer_Freq_Offset :: rat(%d), tx path(%d), freq_offset_khz(%d)
[RF ET][REG CTRL][S5308AP] Get_RFD_Ctrl_Drv_Enable :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP] Get_RFD_Ctrl_Tx_Path_Info :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP] Get_RFD_Ctrl_Tx_Path_Info error (0x%x)
[RF ET][REG CTRL][S5308AP] Get_RFD_Interface_Mode :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP] RegCtrl_Get_Power_Cal_Wait_Time :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP] RegCtrl_Set_Complex_FIR :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5308AP EVT1] Set_Non_LCPU_Ctrl_Reg :: rat(%d), tx path(%d)
[RF ET][REG CTRL][S5133AP EVT0] RegCtrl_dsp_sm_control_off_IPC_Call :: rat(%d), tx path(%d)
