L1LC_InitDb for ST-%d
L1LC_InitCommDb for ST- %d
[gL1LC_DrxState] (%d) -> (%d)
[gL1LC_DRXinSibFlag] (%d) -> (%d)
[gL1LC_ConnDrxConfigFlag] (%d) -> (%d)
[gL1LC_ReInitDrxTriggered] (%d) -> (%d)
[gL1LC_SleepProcOngoing] (%d) -> (%d)
[gDrx_isPagingDoneForMeas] (%d) -> (%d)
[gL1LC_isFirstDrxReq] (%d) -> (%d)
[gDrxServingTimeOOSFlag] (%d) -> (%d)
[gDrxServingTimeOOSFlag_SCG] (%d) -> (%d)
[L1LC_SetNextPagingInstance] (PF: %d PO: %d)
[gL1LC_PagingPalTime] (%u)
[gL1LC_IdleConnDRXStatus] (%d) -> (%d)
[gL1LC_DrxBplmnEnable] (%d) -> (%d)
[bplmn_spare_tmr_duration] (%d) -> (%d)
[gDrx_BplmnStarted] (%d) -> (%d)
[gL1LC_IratUmtsMeasState] (%d) -> (%d)
[gL1LC_IratGsmMeasState] (%d) -> (%d)
[gL1LC_IratGsmVerifyState] (%d) -> (%d)
[gL1LC_IratCdmaMeasState] (%d) -> (%d)
[gL1LC_IratNrMeasState] (%d) -> (%d)
[gL1LC_IratStopPending] (%d) -> (%d)
[gL1LC_IratStopbeforeLatchCnf] (%d) -> (%d)
[gL1LC_IratNrMeasConfigRelease] (%d) -> (%d)
