MSRatTimerCtrl<Register> : MsDoamin(%d), Allocated SID(0x%X), pRatTimer(0x%X)
MSRatTimerCtrl<DeRegister> success : RequestSID(0x%X)
MSRatTimerCtrl<DeRegister> fail : RequestSID(0x%X)
MSRatTimerCtrl<Handle RatTimer Msg> : Not Support MsgId(%d,%s)
MSRatTimerCtrl<Handle RatTimer Msg> : Empty RougingInfo(0x%X)
MSRatTimerCtrl<Update Active Rat> : nullptr RatTimer instance)
MSRatTimerCtrl<Update Active Rat> : RatTmr_MsDomain(%d), Update_MsDomain(%d), CurRatTmrState(%d)
