[RF ET][AT CMD] Set TX Gain command is received err(%d)
[RF ET][AT CMD] Get TX Gain command is received err(%d)
[RF ET][AT CMD] Received command to set SPI S/W mode err(%d)
[RF ET][AT CMD] Received command to set Tx Bandwidth err(%d)
[RF ET][AT CMD] PA Mode change command is received err(%d)
[RF ET][AT CMD] PA Bias change command is received err(%d)
[RF ET][AT CMD] PA Bias change command is received err(%d)
[RF ET][AT CMD] Get SM Info command is received err(%d)
[RF ET][AT CMD] SM Ioctl command is received err(%d)
[RF ET][AT CMD] Get PA Bias All DPD Idx command is received err(%d)
