[RF ET][ET CAL] Set cache On/Off (%d)
[RF ET][AT CMD] Not Supported Delay ENABLE(only DISABLE) : (%d)
[RF ET][AT CMD] Get Inf Handle Drv Info finish (%d, %d, %d)
[RF ET][AT CMD] Get SM Drv Info Error (%d)
[RF ET][AT CMD] Get Modem Ctrl Drv Info Error (%d)
[RF ET][AT CMD] Get Data Inf Drv Info Error (%d)
[RF ET][AT CMD] Set cache data onoff command is received err(%d)
[RF ET][AT CMD] ALL DSP contro OFF command is received err(%d)
[RF ET][AT CMD] Set PA Mode to DSPSHM command is received err(%d)
[RF ET][AT CMD] Set RFIC Gain to DSPSHM command is received err(%d)
[RF ET][AT CMD] Received command to Set Delay To DSPSHM err(%d)
[RF ET][AT CMD] Received command to Get INF HANDLE Drv TX Path :: err(%d)
[RF ET][AT CMD] Received command to Get INF HANDLE Drv TX Path :: err(%d)
[RF ET][AT CMD] Received command to SET_PD_COMP_Off :: err(%d)
[RF ET][AT CMD] FBRX status control command is received err(%d)
[RF ET][AT CMD] Set FBRX Config command is received err(%d)
