>> Fail to send ENDC_INTRA_BAND_ENABLE_NR_CMD
##[NR_SCC] RF FREQSET_CMD: RF DEBUGGING MODE
>> Fail to send FREQSET_NR_CMD
##[NR_SCC] RF FREQSET_CMD: RF DEBUGGING MODE
>> Fail to send FREQSET_NR_CMD (RF_INIT CMD)
##[NR_SCC] RF FREQSET_CMD: RF DEBUGGING MODE
>> Fail to send FREQSET_NR_CMD
>> Fail to send OL_AIT_NR_CMD
>> Fail to send ENDC_INTRA_BAND_ENABLE_NR_CMD
>> Fail to send TX_MODE_CHANGE_NR_CMD
>> Fail to send GAP_CONFIG_NR_CMD
