ARFCN(%d),desiredQbits(%d),measuredY(%d),gainUsed(%d), rssi(%d)
ARFCN(%d),desiredQbits2(%d),measuredY2(%d),gainUsed2(%d), rssi2(%d)
[gmsk_detect_c_1] ch_mode(%d),loopcnt_dbg(%d)
[gmsk_detect_c_2] ch_mode(%d),loopcnt_dbg(%d)
[gmsk_detect_c_2] ch_mode(%d),loopcnt_dbg(%d), [PRX] detection (%d), variance(%d)
[gmsk_detect_c_2] ch_mode(%d),loopcnt_dbg(%d), [DRX] detection (%d), variance(%d)
