[PDSCH_Preproc][TBS_LBRM] DIFF UE CAPA x(%d), CsiRI(%d), maxNumberMIMO_LayersPDSCH(%d)
[PDSCH_Preproc][TBS_LBRM] Invalid x(%d) is replaced to layer(%d), maxNumberMIMO_LayersPDSCH(%d), freqRange(%d)
[PDSCH_Preproc][TBS_LBRM] NrBwpAllDlBwpConfig[%d] BwpId(%d), Length(%d), maxPRBacrossBWPs(%d), s(p)CellCfgInitDlBwpDedi(%d), CcIdx(%d)
[PDSCH_Preproc] TBS_LBRM(%d), maxCodeBlockNum(%d), layer_LBRM(%d), maxPRBacrossBWPs(%d), freqRange(%d), maxMimoLayer.NR_MCFG_IE_CONFIG_FLAG(%d), maxMimoLayer.value(%d), pdschCfgMcsTable.NR_MCFG_IE_CONFIG_FLAG(%d), pdschCfgMcsTable.value(%d)
[PDSCH_Preproc] Invalid DMRS configuration: dmrsType(%d), maxLength(%d)
[PDSCH_Preproc] Invalid 2 CW scheduling within 1 slot[CW:%d]
[PDSCH_Preproc] Invalid DMRS configuration: dmrsType(%d), maxLength(%d)
[PDSCH_Preproc] Invalid DCI format (0x%x)
[PDSCH_Preproc] Discard DCI: RxAntNum(%d) is smaller than layer(%d) in DCI
[PDSCH_Preproc] Discard DCI: CuraSlot(%d) is not matched with dataMover aSlot(%d) in DCI
NrSpDchPreprocDev Discard Second DCI of Same HID in same Slot rx_time.aslot_idx (%d), dlCurTime.aslot_idx(%d)
[PDSCH_Preproc] Decoder Stop after receiving SYS_PARAM_RELEASE[CW:%d]
[PDSCH_Preproc] Discard DCI: Discard Second DCI of Same HID[%d] in same Slot by CW[%d]
[PDSCH_Preproc] (f) DC invalid numLayer : maxMIMOLayers(%d), mumLayer(%d)
[PDSCH_Preproc] Discard DCI: Same HID[%d] transmission within 3 TTI by the differenct DCI format[%d]
[PDSCH_Preproc] DCI of Same HID is parsing twice in continuos slot Harq_id (%d), prevNDI (%d), newNDI (%d), prevRV (%d), newRv (%d), prevAslotIdx (%d), newAslotIdx (%d)
[PDSCH_preproc] invalid antPorts(%d)
[PDSCH_Preproc] Undefined TimeD RA : pCch->pdcchSearchSpace(%d), MultiplexingPattern(%d), pCch->dci1_x.timeResourceAssign(%d)
[PDSCH_Preproc] Invalid RNTI(%d), pdcchSearchSpace(%d)
[PDSCH_Preproc] Invalid TimeD RA : pdschMappingType(%d), dmrsTypeAPosition(%d), S(%d), L(%d), S+L(%d)
[PDSCH_Preproc] Invalid TimeD RA on F slot: nrofDownlinkSymbols(%d) < L(%d)
[PDSCH_Preproc] rvidApplied(%d)
[TdraSiRntiType0ACommon] pdschCfgCommon_timeDomainAllocList.NR_MCFG_IE_CONFIG_FLAG(%d), timeResourceAssign(%d), numList(%d)
[PDSCH_Preproc][RaType0][Low freq SSB] RB_offset(%d), rateMatch_RBG_Idx(%d), rateMatch_RB_Size(%d), rateMatch_PRB_Idx(%d)
[PDSCH_Preproc][RaType0][high freq SSB] RB_offset(%d), rateMatch_RBG_Idx(%d), rateMatch_RB_Size(%d), rateMatch_PRB_Idx(%d)
[PDSCH_Preproc][RaType0][SSB_OUTSIDE_BWP] Org: numRbg(%d), firstRbgSize(%d), lastRbgSize(%d), rbgBitmap(%d), RbgSize(%d), Modi: numRbg(%d), firstRbgSize(%d), lastRbgSize(%d), rbgBitmap(%d), rbgBitmap1(%d)
[PDSCH_Preproc][RaType1] freqRange : %d, RB_start(%d), L_RBs(%d), FDRA(%d), prb Length (%d)
[PDSCH_Preproc] Invalid FreqD RA : numPRBwithinBWP(%d)
[PDSCH_preproc] DCI 1_0 in CSS: RB_start(%d), L_RBs(%d), vrb2prb(%d), coresetZeroRbSize(%d), coresetStartRb(%d), pdcchSearchSpace(%d), rntiIdx(%d), detectedCoreset(%d)
[PDSCH_Preproc] Invalid FDRA : RA_type(%d), FDRA(%d), BWP_prbLength(%d), RB_start(%d), L_RBs(%d)
[PDSCH_Preproc] Invalid FreqD RA : pCch->ratype(%d)
[PDSCH_Preproc] Invalid FDRA : N_PRB(%d)
[PDSCH_Preproc] Overlap FreqD RA between CW0 and CW1: CW0_RBStart(%d), CW0_LRBs(%d), CW1_RBStart(%d), CW1_LRBs(%d)
[PDSCH_preproc][ResourceAllocFreq_CalcType0RB] SsbBwpStatusFlag(%d), RBOffset_L(%d), RBOffset_H(%d), tComNumRbg(%d), rbgBitmap(0x%x), firstRbgSize(%d), lastRbgSize(%d), RbgSize(%d)
[PDSCH_Preproc] ra_type(%d), numRbg(%d), RbgSize(%d), firstRbgSize(%d), lastRbgSize(%d), n_PRB(%d)
[PDSCH_preproc] Vrb2PrbInterleaver ON : DCI(0x%x), SI_RNTI(%d), search space(%d), CoreSetIdx(%d), coresetZeroRbSize(%d), nr_demod_system_info(0x%x)
[PDSCH_preproc] Vrb2PrbInterleaver ON : invalid bwp_start_rb_index(%d)
[PDSCH_preproc] Vrb2PrbInterleaver ON : DCI(0x%x), search space(%d), coresetZeroRbSize(%d), NrSpBandwidthPartDLInfo.startCrb(%d), coresetStartRb(%d), first_prg_offset(%d)
[PDSCH_preproc] Vrb2PrbInterleaver Invalid: pdsch_start_symbol_index(%d), pdsch_symbol_num(%d), interleaving_size(%d), interleaving_shift(%d), dl_rb_num(%d)
[PDSCH_preproc] Vrb2PrbInterleaver ON : End_RB_index(%d), Local_End_RB_index(%d), interleaving_shift(%d), End_bundle_index(%d), N_bundle(%d), Start_Bundle_index(%d)
[PDSCH_preproc] mcs_C_RNTI.NR_MCFG_IE_CONFIG_FLAG(%d), pdschCfgMcsTable.NR_MCFG_IE_CONFIG_FLAG(%d), pdschCfgMcsTable.value(%d), rntiIdx(%d), pdcchSearchSpace(%d), mcsTableIdx(%d)
[PDSCH_preproc] mcs_C_RNTI.NR_MCFG_IE_CONFIG_FLAG(%d), rntiIdx(%d), mcsTableIdx(%d)
[PDSCH_preproc] spsCfgMcsTable.NR_MCFG_IE_CONFIG_FLAG(%d), pdschCfgMcsTable.NR_MCFG_IE_CONFIG_FLAG(%d), pdschCfgMcsTable.value(%d), format(%d), rntiIdx(%d), using SPS-config(%d), mcsTableIdx(%d)
[PDSCH_preproc] spsCfgMcsTable.NR_MCFG_IE_CONFIG_FLAG(%d), spsCfgMcsTable.value(%d), rntiIdx(%d), using SPS-config(%d), mcsTableIdx(%d)
[PDSCH_Preproc] Invalid MCS on P_RNTI/RA_RNTI/SI_RNTI (Qm>2): rnti(%d), modOrder(%d)
[PDSCH_Preproc] Invalid CalcDmrsRE dmrsCfgType(%d)
[PDSCH_Preproc] Invalid DmrsRE NR_PDSCH_MAPPING_TYPE_B : durationInSymbols(%d), cpType(%d)
[PDSCH_Preproc] Invalid CalcDmrsRE dmrsAddPos(%d) for len2
[PDSCH_Preproc] Invalid CalcDmrsRE dlDmrsMaxLength(%d), dmrsMappingType(%d)
[PDSCH_Preproc] Invalid CalcDmrsRE rntiIdx(%d)
[PDSCH_Preproc] Invalid TB_scaling field(%d)
[PDSCH_Preproc] Invalid Trbk calculation: newTx(%d), tbs(%d), tbRst(%d)
[PDSCH_Preproc] Invalid Trbk calculation: newTx(%d), mcsTable(%d), Imcs(%d)
[PDSCH_Preproc] Invalid Trbk calculation: mcsTable(%d), Imcs(%d)
[PDSCH_Preproc] different Trbk size with previous one tbs(%d), prevTbs(%d), newTx(0x%08x)
[PDSCH_Preproc] Invalid TBS exceeding 2976 bits with SI_RNTI(%d) TBS(%d)
[PDSCH_Preproc] DL grant report skip: TimeAlignmentTimer state (%d)
(I) Block sendling PHY_PHY_DlGrantReport from scell during sysparam change handlig
[PDSCH_Preproc] N_info BTW 3824_3825
[PDSCH_Preproc] NrSpSchDec(cc_idx=%d) cw:%d cbg infor is different with previous one when reTx: cbg:0x%08x(0x%08x)
[NrSpSchPreProc] Remove storeDciIdx(%d) because this DCI is false alarm
[NR IPC][NR_BWPSWITCH_EVT_DCI_1_1] PHY_PHY_BWP_SWITCHING_CTRL_IND, Dst(%d)/Src(%d)/curBwpIdx(%d)/BwpInd(%d)/numConfigured(%d)
[NR IPC][NR_BWPSWITCH_EVT_DCI_1_1] PHY_PHY_BWP_SWITCHING_CTRL_IND, discard BWP Switching due to False Alarm!!
[PDSCH_Preproc] NrSpSchDec(cc_idx=%d) ack2Nack harqProcNum:%d, newTx:0x%08x, tbRslt:0x%08x, decSkip:0x%08x, pdschAck2NackCnt:%d
[PDSCH_Preproc] NrSpSchDec(cc_idx=%d) pdschResidualErrCnt harqProcNum:%d, newTx:0x%08x, tbRslt:0x%08x, decSkip:0x%08x, pdschResidualErrCnt:%d
[PDSCH_Preproc] Invalid channel : decSkip(0x%x)
[PDSCH_Preproc] Set newTx NR_NEW_RXMODE_MISMATCH_MASK : previous decSkip(0x%x), harqProcNum(%d), newTx(%x)
[PDSCH_Preproc] Set newTx NR_NEW_PDSCH_DELAY_MASK : previous decSkip(0x%x), harqProcNum(%d), newTx(%x)
[PDSCH_preproc][FdmCchSch] [FD] dci_start(%d), dci_end(%d), schPrbStart(%d), schPrbEnd(%d), [TD] coreset_start(%d), coreset_len(%d)
[MDFS] NrSch SetDfsApi(ON), rtg_s(%d), rtg_e(%d), rtg diff(%d)
(I)Invalid Type(%d)
