[NRUECAPA] Registry NRCAPA.BANDCOMB_ENABLE_FR2_8CC(%d)
[NRUECAPA] Registry NRCAPA.BANDCOMB_ENABLE_FR2(%d)
[NRUECAPA] Registry Band.BwpSameNumerology(%d)
[NRUECAPA] Registry Band.BwpDiffNumerology(%d)
[NRUECAPA] Registry Band.MaxNumMimoLayersCbPusch(%d)
[NRUECAPA] Registry Band.MaxNumSrsResourcePerSet(%d)
[NRUECAPA] Registry Band.MaxNumSrsPortsPerResource(%d)
[NRUECAPA] Registry Gen.SrsTxSwitch(%d)
[NRUECAPA] Band(%d) cc(%d) PowerClassPerBand(%d)
[NRUECAPA] Registry Fsdl.AddDmrsDlAlt(%d)
[NRUECAPA] Registry Gen.PdcchMonSingOcc(%d)
[NRUECAPA] Registry Band.RateMatchLteCrs(%d)
[NRUECAPA] Registry Switch.DssFeature(%d)
[NRUECAPA] Registry Gen.RateMatchRsrcSetSemiStat(%d)
[NRUECAPA] Registry NRSM.RQosSupport (%d)
[NRUECAPA] Registry Gen.VoiceOverNrFrx (%d)
[NRUECAPA] Registry Gen.DynamicPowerSharing (%d)
[NRUECAPA] Registry Gen.HighSpeedParameters (%d)
[NRUECAPA] Registry Gen.OnDemandSIBConnected (%d)
[NRUECAPA] Registry Gen.McgRLFRecoveryViaSCG (%d)
[NRUECAPA] Registry HCOMMON.GCFMODE (%d)
[NRUECAPA] Registry LTEL1.SAFEDV_ENABLE (%d)
[NRUECAPA] Registry NR.CONFIG.MODE (%d)
[NRUECAPA] Registry NR.CONFIG.MODE (%d), Stack Id (%d)
[NRUECAPA] Registry LTENR.NSA.UECAPA.NR.GEN.DRX.CYCLE (%d)
[NRUECAPA] Registry NRCAPA_DB_SETTING_MODE (%d)
[NRUECAPA] Registry NRCAPA_DSDS_CHECKMODE (%d)
[NRUECAPA] Registry OMC.BASED.DSS.PLMN.ENABLE (%d)
[NRUECAPA] Registry OMC.DSS.PLMN.LIST.MODE (NSA)ALLOW=0x1/BLOCK=0x2, (SA)ALLOW=0x4/BLOCK=0x8 (0x%X)
[NRUECAPA] Registry OMC.DSS.PLMN.LIST.COUNT 'NSA'(%d)
[NRUECAPA] Registry OMC.DSS.PLMN.LIST 'NSA'List # %d MCC(%X%X%X) MNC(%X%X%X)
[NRUECAPA] Registry OMC.NR.SA.DSS.PLMN.LIST.COUNT 'SA' (%d)
[NRUECAPA] Registry OMC.NR.SA.DSS.PLMN.LIST 'SA' List # %d MCC(%X%X%X) MNC(%X%X%X)
[NRUECAPA] Registry NRCAPA_SUPERSET_BANDCOMB_MODE (%d)
[NRUECAPA] Registry Gen.IdleInactiveMeas (%d)
[NRUECAPA] Registry NRCAPA_BANDTYPE_SETTING_MODE (%d)
[NRUECAPA] Registry TCS_Is_Carrier_Config_Applied (%d)
[NRUECAPA] Registry TCS voiceOverNR (%d)
[NRUECAPA] Registry TCS CRSRateMatching (%d)
[NRUECAPA] Registry TCS SAn2Enabled (%d)
[NRUECAPA] Registry TCS SAn41Enabled (%d)
[NRUECAPA] Registry TCS SAn25Enabled (%d)
[NRUECAPA] Registry TCS SAn66Enabled (%d)
[NRUECAPA] Registry TCS SAn71Enabled (%d)
[NRUECAPA] Registry SRVCC_ENABLED (%d)
[NRUECAPA] Registry GetSpType (0x%X)
[NRUECAPA] Registry !LTENR.NSA.DRB.UL.SPLIT.SUPPORT (%d)
[NRUECAPA] Registry GetFciInfo (%d)
[NRUECAPA] Registry NRRRC.R16_UAI_SUPPORT (%d)
[NRUECAPA] !NRRRC_SA_AS_RELEASE_VER (%d)
[NRUECAPA] Registry NRCAPA.Gen.VoiceFallbackInd (%d)
[NRUECAPA] Registry !NRCAPA_NON_SHARED_SPECTRUM_CH_ACCESS (%d)
[NRUECAPA] Registry !NRCAPA_SHARED_SPECTRUM_CH_ACCESS (%d)
[NRUECAPA] Registry !NRCAPA_POWSAVE_MODE (%d)
[NRUECAPA] Registry !NRCAPA_POWSAVE_MIN_SCHEDULING_OFFSET_PREFERENCE (%d)
[NRUECAPA] Registry !NRCAPA_POWSAVE_MAXBW_PREFERENCE (%d)
[NRUECAPA] Registry !NRCAPA_POWSAVE_MAXMIMO_LAYER_PREFERENCE (%d)
[NRUECAPA] Registry !NRCAPA_NSA_HPUE_SUPPORTED (%d)
[NRUECAPA] Registry !NRCAPA_NRCA_SUPPORT_CHECK (%d)
