[N :MM,%d] [%s,%d] SetNextNrmmState state(%s,%s)
[N :MM,%d] [%s,%d] SetNextNrmmState state(%s,%s)
[N :MM,%d] [%s,%d] SetNextNrmmState state(%s,%s)
[N :MM,%d] [%s,%d] SetNextNrmmState state(%s,%s)
[N :MM,%d] [%s,%d] SetNextNrmmState state(%s,%s)
[N :MM,%d] [%s,%d] SetNextNrmmState state(%s,%s)
[N :MM,%d] [%s,%d] SetNextNrmmState state(%s,%s)
[N :MM,%d] [%s,%d] SetNextNrmmState state(%s,%s)
