>>> GHAL_Stub called L1AlNvramInitialise()
>>> GHAL_Stub called CfL1BgSystemInitialise()
>>> GHAL_Stub called CfL1BgSystemActive()
>>> GHAL_Stub called L1BgIdleInitialise()
>>> GHAL_Stub called L1TimersInitialise()
>>> GHAL_Stub called L1BgInitTcbAllocation()
>>> GHAL_Stub called L1FrInitTriggerControl()
>>> GHAL_Stub called L1FrNullInit()
