L2_HAL_LMAC_RESET_IND was received. L2 will trigger RRC_L2_MAX_RETX_FAIL_IND. CellGrpId(%d) bLocalRelease(%d)
[L2] Sending RRC_L2_MAX_RETX_FAIL_IND Fail!
[L2->RRC] RRC_L2_MAX_RETX_FAIL_IND
[L2] L2_L2HPDCPRXDELIV_DATA_IND
[ERROR] AllocMsg fail!
[ERROR] AllocMsgBodyElem fail!
[ERROR] SendMsg fail!
[L2] RRC_L2_DATA_IND, m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2HPDCPRXDELIV_INTEGRITY_CHECK_FAIL_IND
[L2] Sending RRC_L2_INTEGRITY_CHECK_FAIL_IND Fail!
[L2] RRC_L2_INTEGRITY_CHECK_FAIL_IND m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2HPDCPRX_DATA_IND
[ERROR] AllocMsg fail!
[ERROR] AllocMsgBodyElem fail!
[ERROR] SendMsg fail!
[L2] RRC_L2_DATA_IND m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2HPDCPRX_INTEGRITY_CHECK_CNF
[L2] Sending RRC_L2_INTEGRITY_CHECK_CNF Fail!
[L2] RRC_L2_INTEGRITY_CHECK_CNF m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2HPDCPRX_INTEGRITY_CHECK_FAIL_IND
[L2] Sending RRC_L2_INTEGRITY_CHECK_FAIL_IND Fail!
[L2] RRC_L2_INTEGRITY_CHECK_FAIL_IND m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2HPDCPRX_REESTABLISH_CNF
[L2] Sending RRC_L2_RESET_CNF Fail
[L2] RRC_L2_RESET_CNF m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2HPDCPRX_SECURITY_DATA_IND
[ERROR] AllocMsg fail!
[ERROR] AllocMsgBodyElem fail!
[ERROR] SendMsg fail!
[L2] RRC_L2_SECURITY_DATA_IND m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2HPDCPTX_DATA_CNF
[L2] Sending RRC_L2_DATA_CNF Fail
[L2] RRC_L2_DATA_CNF m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2HPDCPTX_RELEASE_CNF
[L2] Sending RRC_L2_RELEASE_CNF Fail
[L2] RRC_L2_RELEASE_CNF m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2HPDCPTX_SECURITY_CONFIG_CNF
[L2] Sending RRC_L2_SECURITY_CONFIG_CNF Fail
[L2] RRC_L2_SECURITY_CONFIG_CNF m_DomainType[%d] CellGrpId[%d]
[L2] Sending L2_L2HPDCPTX_FAIL_IND Fail!
[L2] L2_L2HPDCPTX_FAIL_IND by PdcpTx m_DomainType[%d] CellGrpId[%d]
[L2] Sending RRC_L2_MAX_RETX_FAIL_IND Fail!
[L2] RRC_L2_MAX_RETX_FAIL_IND by RlcRx m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2LMACRACH_CONFIG_CNF
[L2] Sending RRC_L2_CONFIG_CNF Fail!
[L2] RRC_L2_CONFIG_CNF m_DomainType[%d] CellGrpId[%d]
L2_L2LMACRACH_RACH_START_CNF_Handler start
RRC_L2_RACH_START_CNF send fail
[L2] RRC_L2_RACH_START_CNF m_DomainType[%d] CellGrpId[%d]
L2_L2LMACRACH_RACH_STATUS_IND_Handler start
RRC_L2_RACH_STATUS_IND send fail
[L2] RRC_L2_RACH_STATUS_IND Result[%d] m_DomainType[%d] CellGrpId[%d]
L2_L2LMACRACH_RACH_STOP_CNF_Handler start
RRC_L2_RACH_STOP_CNF send fail
[L2] RRC_L2_RACH_STOP_CNF m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2LMACRX_DATA_IND
[ERROR] AllocMsg fail!
[ERROR] AllocMsgBodyElem fail!
[ERROR] SendMsg fail!
[L2] RRC_L2_DATA_IND m_DomainType[%d] CellGrpId[%d]
[L2] Sending RRC_L2_MAX_RETX_FAIL_IND Fail!
[L2] RRC_L2_MAX_RETX_FAIL_IND LcId[%d] Dup[%d] m_DomainType[%d] CellGrpId[%d]
L2_L2LMACRACH_PUCCH_SRS_RELEASE_IND_Handler start
RRC_L2_PUCCH_SRS_RELEASE_IND send fail
[L2] RRC_L2_PUCCH_SRS_RELEASE_IND m_DomainType[%d] CellGrpId[%d]
L2_L2LMACRX_PUCCH_SRS_RELEASE_IND_Handler start
RRC_L2_PUCCH_SRS_RELEASE_IND send fail
[L2] RRC_L2_PUCCH_SRS_RELEASE_IND m_DomainType[%d] CellGrpId[%d]
L2_L2LMACRACH_BWP_CHANGE_DONE_IND_Handler start
RRC_L2_BWP_CHANGE_DONE_IND send fail
[L2] RRC_L2_BWP_CHANGE_DONE_IND m_DomainType[%d] CellGrpId[%d]
[L2] L2_RRC_DATA_REQ m_DomainType[%d] CellGrpId[%d]
[L2] Sending L2_RRC_DATA_REQ_Handler Fail!
[L2] L2HPDCPTX_L2_DATA_REQ m_DomainType[%d] CellGrpId[%d]
[L2] L2_RRC_INTEGRITY_CHECK_REQ
[L2] Sending L2HPDCPRX_L2_INTEGRITY_CHECK_REQ Fail!
[L2] L2HPDCPRX_L2_INTEGRITY_CHECK_REQ m_DomainType[%d] CellGrpId[%d]
[L2] L2_RRC_SECURITY_CONFIG_REQ
[L2] Sending L2HPDCPRX_L2_SECURITY_CONFIG_REQ Fail!
[L2] L2HPDCPRX_L2_SECURITY_CONFIG_REQ m_DomainType[%d] CellGrpId[%d]
