[L2] L2_L2HPDCPRX_CONFIG_CNF
[L2] Sending L2HPDCPTX_L2_CONFIG_REQ Fail!
[L2] L2HPDCPTX_L2_CONFIG_REQ m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2HPDCPRX_NR_DL_RBINFO_IND
[L2] Sending LTEPDCP_L2_NR_DL_RBINFO_IND Fail!
[L2] LTEPDCP_L2_NR_DL_RBINFO_IND
[L2] L2_L2HPDCPRX_RELEASE_CNF
[L2] Sending L2HPDCPTX_L2_RELEASE_REQ Fail
[L2] L2HPDCPTX_L2_RELEASE_REQ m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2HPDCPRX_SECURITY_CONFIG_CNF
[L2] Sending L2HPDCPTX_L2_SECURITY_CONFIG_REQ Fail!
[L2] L2HPDCPRX_L2_SECURITY_CONFIG_REQ m_DomainType[%d] CellGrpId[%d]
[L2] Sending L2HPDCPTX_L2_TX_PAUSE_REQ Fail!
[L2] Sending L2HPDCPTX_L2_TX_RESUME_REQ Fail!
[L2] L2_L2HPDCPTX_NR_UL_RBINFO_IND
[L2] Sending LTEPDCP_L2_NR_UL_RBINFO_IND Fail!
[L2] LTEPDCP_L2_NR_UL_RBINFO_IND
[L2] Sending LTEPDCP_L2_NR_UL_RLCBO_REQ Fail!
[L2] Sending LTEPDCP_L2_NR_PDCPBO_UPDATE_IND Fail!
[L2] L2_L2HPDCPTX_REESTABLISH_CNF
[L2] Sending L2HPDCPRX_L2_REESTABLISH_REQ Fail
[L2] L2HPDCPRX_L2_REESTABLISH_REQ m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2HPDCPTX_NR_UL_CIPHER_KEY_IND
[L2] Sending LTEPDCP_L2_NR_UL_CIPHER_KEY_IND Fail!
[L2] LTEPDCP_L2_NR_UL_CIPHER_KEY_IND
[L2] L2_L2HPDCPTX_NR_UL_DATA_IND
[L2] Sending LTEPDCP_L2_NR_UL_DATA_IND Fail!
[L2] LTEPDCP_L2_NR_UL_DATA_IND
[L2] L2_L2HRLCRETX_RELEASE_CNF
[L2] Sending L2HPDCPRX_L2_RELEASE_REQ Fail!
[L2] L2HPDCPRX_L2_RELEASE_REQ m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2HRLCRETX_REESTABLISH_CNF
[L2] Sending L2HPDCPTX_L2_REESTABLISH_REQ Fail!
[L2] L2HPDCPTX_L2_REESTABLISH_REQ m_DomainType[%d] CellGrpId[%d]
[L2] Sending L2HPDCPRX_L2_TX_PAUSE_REQ fail
[L2] Sending L2HPDCPRX_L2_TX_RESUME_REQ fail
[L2] L2_L2LMACTX_CONFIG_CNF
[L2] Sending L2HPDCPRX_L2_CONFIG_REQ Fail!
[L2] L2_LTEPDCP_LTE_DL_RBINFO_IND
[L2] Sending L2_LTEPDCP_LTE_DL_RBINFO_IND Fail!
[L2] L2HPDCPRX_L2_LTE_DL_RBINFO_IND
[L2] L2_LTEPDCP_LTE_UL_RBINFO_IND
[L2] Sending L2HPDCPTX_L2_LTE_UL_RBINFO_IND Fail!
[L2] L2HPDCPTX_L2_LTE_UL_RBINFO_IND
[L2] L2_RRC_LTE_DL_RBINFO_IND
[L2] Sending L2HPDCPRX_L2_LTE_DL_RBINFO_IND Fail! (RB_ID=%d IsSrb=%d)
[L2] L2HPDCPRX_L2_LTE_DL_RBINFO_IND[%d] (RB_ID=%d IsSrb=%d)
[L2] L2_RRC_LTE_UL_RBINFO_IND
[L2] Sending L2HPDCPTX_L2_LTE_UL_RBINFO_IND Fail! (RB_ID=%d IsSrb=%d)
[L2] Sending L2HPDCPTX_L2_LTE_UL_RBINFO_IND Fail! (RB_ID=%d IsSrb=%d)
[L2] L2HPDCPTX_L2_LTE_UL_RBINFO_IND[%d] (RB_ID=%d IsSrb=%d)
[L2] Sending L2HPDCPTX_L2_LTE_UL_RLCBO_CNF Fail!
[L2] L2_PDNMGR_UPDATE_SESSION_INFO_IND
[L2] L2_PDNMGR_UPDATE_SESSION_INFO_IND Fail
[L2] L2_RRC_BEARER_CHANGE_IND
[L2] Sending L2_RRC_BEARER_CHANGE_IND Fail!
[L2] L2HPDCPTX_L2_BEARER_CHANGE_IND
[L2] Sending L2HPDCPTX_L2_PENDING_NEW_DATA_REQ Fail!
[L2] L2HPDCPTX_L2_PENDING_NEW_DATA_REQ m_DomainType[%d] CellGrpId[%d]
[L2] L2_RRC_COUNT_VALUE_REQ_Handler (TransactionId)(%d)
[L2] L2_RRC_RB_CHANGE_IND
[L2] Sending L2HPDCPRX_L2_RB_CHANGE_IND Fail!
[L2] L2HPDCPRX_L2_RB_CHANGE_IND
[L2] Sending L2HPDCPTX_L2_RB_CHANGE_IND Fail!
[L2] L2HPDCPTX_L2_RB_CHANGE_IND m_DomainType[%d] CellGrpId[%d]
[L2] Sending L2HPDCPRX_L2_SECURITY_DATA_FAIL_IND Fail!
[L2] L2HPDCPRX_L2_SECURITY_DATA_FAIL_IND
[L2] CellGrpId(0x%02x)
[L2] CellGrpId(0x%02x)
[LcId:0x%02x] Wrong LcId
[ERROR] AllocMsg fail!
[L2] TransactionId:%d, DrbCountInfoCount:%d
[ERROR] SendMsg fail!
[L2] RRC_L2_COUNT_VALUE_CNF
