[L2] L2_L2HPDCPTX_PENDING_NEW_DATA_CNF
[L2] Sending L2HRLCRX_L2_CONFIG_REQ Fail!
[L2] L2HRLCRX_L2_CONFIG_REQ m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2HRLCRX_CONFIG_CNF
[L2] Sending L2HRLCTX_L2_CONFIG_REQ Fail!
[L2] L2HRLCTX_L2_CONFIG_REQ m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2HRLCRX_RELEASE_CNF
[L2] Sending L2HRLCTX_L2_RELEASE_REQ Fail!
[L2] L2HRLCTX_L2_RELEASE_REQ m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2HRLCRX_REESTABLISH_CNF
[L2] Sending L2HRLCTX_L2_REESTABLISH_REQ Fail!
[L2] L2HRLCTX_L2_REESTABLISH_REQ m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2HRLCTX_CONFIG_CNF
[L2] Sending L2HRLCRETX_L2_CONFIG_REQ Fail!
[L2] L2HRLCRETX_L2_CONFIG_REQ m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2HRLCTX_RELEASE_CNF
[L2] Sending L2HRLCRETX_L2_RELEASE_REQ Fail!
[L2] L2HRLCRETX_L2_RELEASE_REQ m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2HRLCTX_REESTABLISH_CNF
[L2] Sending L2HRLCRETX_L2_REESTABLISH_REQ Fail!
[L2] L2HRLCRETX_L2_REESTABLISH_REQ m_DomainType[%d] CellGrpId[%d]
[L2] Sending L2HRLCTX_L2_TX_RESUME_REQ fail
[L2] Sending L2HRLCRX_L2_TX_RESUME_REQ fail
[L2] L2_L2LMACRX_CONFIG_CNF
[L2] Sending L2HRLCRX_L2_RELEASE_BY_CONFIG_IND_T Fail!
[L2] Sending L2HRLCRETX_L2_RELEASE_BY_CONFIG_IND_T Fail!
[L2] Sending L2LMACRACH_L2_CONFIG_REQ Fail!
[L2] L2LMACRACH_L2_CONFIG_REQ m_DomainType[%d] CellGrpId[%d]
[L2] L2_L2LMACTX_RESET_CNF
[L2] Sending L2HRLCRX_L2_REESTABLISH_REQ Fail!
[L2] L2HRLCRX_L2_REESTABLISH_REQ m_DomainType[%d] CellGrpId[%d]
[L2] Sending L2HRLCRX_L2_RELEASE_REQ Fail!
[L2] L2HRLCRX_L2_RELEASE_REQ m_DomainType[%d] CellGrpId[%d]
[L2] Sending L2HRLCRX_L2_CONFIG_REQ Fail!
[L2] L2HRLCRX_L2_CONFIG_REQ m_DomainType[%d] CellGrpId[%d]
