[ReassemblyBuffer] NackSn[%d %d] NackOffset[%d %d]
[ReassemblyBuffer] Discard invalid data Sn[%d] RecvSO[%d] RecvEO[%d] LastEO[%d] LastSeg[%d]
[ReassemblyBuffer] Discard invalid data Sn[%d] RecvSO[%d] RecvEO[%d] LastEO[%d] LastSeg[%d]
[ReassemblyBuffer] Discard invalid data Sn[%d] RecvSO[%d] RecvEO[%d] LastEO[%d] LastSeg[%d]
[ReassemblyBuffer] Out-of-window RecvSn(%d), Vr_r(%d), m_ConnSn(%d)
[ReassemblyBuffer] Discard duplicate data Sn[%d]
[ReassemblyBuffer] NackSN[%d, %d] NackOffset[%d, %d] RecvSN[%d] RecvSO[%d] RecvEO[%d]
[ReassemblyBuffer] NackSN[%d, %d] NackOffset[%d, %d] RecvSN[%d] RecvSO[%d] RecvEO[%d]
[ReassemblyBuffer] ValidNackNode[0x0] RecvSN[%d] RecvSO[%d] RecvEO[%d]
[ReassemblyBuffer] NACK_PROC_RLT_DELETE, m_pFirstNackNode[0x0]
[ReassemblyBuffer] NACK_PROC_RLT_MODIFY, m_pLastNackNode[0x0]
[ReassemblyBuffer] NACK_PROC_RLT_DELETE, m_pLastNackNode[0x0]
[ReassemblyBuffer] pStartNackNode[0x%X] pEndNackNode[0x%X]
[ReassemblyBuffer] pNewNackNode[0x0]
[ReassemblyBuffer] pValidNackNode[0x0] NackListEmpty[0]
[ReassemblyBuffer] pValidNackNode[0x0]
[ReassemblyBuffer] pFirstNackNode[0x0]
[ReassemblyBuffer] pNewNackNode[0x0]
[ReassemblyBuffer] pValidNackNode[0x0] NackListEmpty[0]
[ReassemblyBuffer] m_pLastNackNode[0x0]
[ReassemblyBuffer] invalid pDesc[0x0]
[ReassemblyBuffer] DATA[NONE]
[ReassemblyBuffer][ERROR][SN:%d] L2HRX_GetDescriptor error, [pDescTerminal:0x%X] [ppStart:0x%X] [ppEnd:0x%X]
[ReassemblyBuffer][ERROR] Rest StartSn[%d] EndSn[%d] CurSN[%d]
[ReassemblyBuffer] pNewNackNode[0x0]
[ReassemblyBuffer] [E] L2HRX_GetNextP [0x0]
[ReassemblyBuffer][eReasmAct:%d][SN:%d][SO:%d][PayloadLen:%d][CurHistoryIdx:%d/%d]
