Received Socket Open() in Wrong State.
Received Socket Bind() in Wrong State.
Received Socket Connect() in Wrong State.
Received Socket Recv() in Wrong State.
Received Socket RecvFrom() in Wrong State.
Received Socket RecvFrom() in Wrong State.
Received Socket Send() in Wrong State.
Received Socket SendTo() in Wrong State.
Received Socket Close() in Wrong State.
Received Socket Shutdown() in Wrong State.
