##[NR_SCC] NR RF INFO : idx(%d), bitmask(0x%x), band(%d), freq(%d), bw(%06d), prx_bitmask(0x%x), rx_beam_idx(0x%x)
##[NR_SCC][WARNING] InitPath : Abnormal rf_path_idx(%d)
##[NR_SCC] InitPath : rf_path_idx(%d)
##[NR_SCC] ReadRegModuleSwitchMode : set m_module_switch_mode(%d -> %d)
##[NR_SCC] GetDrxMeasMode(%d)
##[NR_SCC] SetDrxMeasMode(%d -> %d)
##[NR_SCC][WARNING] CheckRfPathIdxBoundary : Abnormal rf_path_idx(%d)
##[NR_SCC][WARNING] CheckRfOn : Abnormal rf_path_idx(%d)
##[NR_SCC] CheckRfOn(%d)
