##[NR_MEAS] %s, MeasRatType(%d) Lte.MeasMode(%d) Utra.MeasMode(%d)
##[NR_MEAS] %s earfcn(%d) numOfCells(%d) AGC1(%d) AGC2(%d)
##[NR_MEAS] %s cellId(%d) cpType(%d) rsrp(%d) rsrq(%d) sinr(%d) TimingOffset(%d)
##[NR_MEAS] %s MeasRatType(%d) MeasMode(%d) ObjectId(%d) CarrierFreq(%d) NumResult(%d)
##[NR_MEAS] %s CellId(%d) Rssi(%d) Rscp(%d) EcNo(%d) TimingOffset(%d)
##[NR_MEAS] %s, #%d: CorrEnergy(%d), BeamTimingOffset(%d), CellId(%d) RxBeamIdx(%03x)
##[NR_MEAS]DSIFP] %d: %u, %u, %u, %u
##[NR_MEAS] Fail CNF for MeasMode(%d)!!
##[NR_MEAS] PathConfig : RxBeamIdx(0x%03x)
##[NR_MEAS][3ABB][CONFIG] ConfigRxBeamIdx(0x%03x) vh_path(%d) //[MAP] module_map(%x) beam_map(%x) vh_map(%x)
##[NR_MEAS] gapStartRemainTime (%d) MinMeasUseTime (%d)
##[NR_MEAS] Send PATH_CONFIG_REQ:: req_type(%d) num_of_cfg_cell(%d), scell_idx(%d), freq_info(%d, %d, %d), bw(%d)
##[NR_MEAS] (ReleaseModule) module_op_type(%d) rx_beam_idx(0x%03x) vh_path(%d0 trig_mask_en(%d)
##[NR_MEAS] SendSCCPathRelease: num_rel_cell(%d), cell_info_idx(%d), skip_rf_path_off(%d)
##[NR_MEAS] SendModuleSwitchReq : SwType(%d) OpType(%d) RxbeamIdx(0x%03x) vh_path(%d)
##[NR_MEAS] Skip Send_L1C_L1C_SCCCTRLR_PATH_CONFIG_REQ_FOR_N2X, PathConfigForN2X(%d)
##[NR_MEAS] Send_L1C_L1C_SCCCTRLR_PATH_CONFIG_REQ_FOR_N2X, num_of_cfg_cell(%d) num_of_rel_cell(%d) is_irat(%d)
##[NR_MEAS] %s, Send: Send_L1C_L1C_SCCCTRLR_RESOURCE_REQ to SRCHCTRLR: Mode(%d)
##[NR_MEAS] %s, Send: Send_L1C_L1C_SCCCTRLR_RESOURCE_REQ to SRCHCTRLR: Mode(%d)
##[NR_MEAS][RBS] RBSType(%d), CandidateBeamMap(0x%d) RxBeamIdx(%03x)
##[NR_MEAS] MeasMode(%d), NumCell(%d), Band(%d), Arfcn(%d), Numerology(%d), Period(%d), PathIdx(%d)
##[NR_MEAS] <MEAS_STOP> during the rxbeam_sweeping Prev_rbs(%d) -> INIT with BeamMap(%x)
##[NR_MEAS] N2XMeas Schedule! Send: MEAS_REQ to MMCIFCTRLR, MeasMode(%d) MeasRatType(%d) CarrierFreq(%d) NumLteMeasInput(%d) ScellIdx(%d) MeasMethod(%d) N2XMeasStartIdx(%d)
##[NR_SCC] Send_L1TUNNEL_L1C_4G_NR_INFO_REQ : gap_start_time(%d), gap_length(%d), rtg_diff(%d)
##[NR_MEAS] CalcCsiMeasBw PtA_arfcn(%u) PtA_Freq(%u) CsiRs_Scs(%d)
##[NR_MEAS] CalcCsiMeasBw CellIdx[%d]: StartPRB(%u) nPRB(%u) FreqStart(%u) FreqEnd(%u)
##[NR_MEAS] CalcCsiMeasBw INVALID! CellIdx[%d]: StartPRB(%u) nPRB(%u)
##[NR_MEAS] CalcCsiMeasBw MeasBWFreqStart(%u) MeasBWFreqEnd(%u) BwInFreq(%u)
##[NR_MEAS] CalcCsiMeasBw MeasBW_ceiled(%u) CenterFreq(%u) CenterArfcn(%u)
##[NR_MEAS] Invalid CSI RS SCS (%d)
