[L2LMACTX] L2LMACTX_L2HRLCRETX_UPDATE_RLCTX_NACK_REQ
[L2LMACTX] Ignore L2LMACTX_L2HRLCRETX_UPDATE_RLCTX_NACK_REQ
[L2LMACTX] L2LMACTX_L2HRLCRX_STATUS_FULL_IND
[L2LMACTX] L2LMACTX_L2HRLCTX_DISCARD_DONE_IND CellGrpId[%d]
[L2LMACTX] DiscardSize:%d, PrevBo:%d, Bo:%d
[L2LMACTX] L2LMACTX_L2HRLCTX_NEW_TX_STOP_REQ [LcId:%d] [Cause:%d]
[L2LMACTX] Init ReTxDataVolume for LcId%d
[L2LMACTX] L2HRLCTX_L2LMACTX_NEW_TX_STOP_CNF
[L2LMACTX] L2LMACTX_L2HRLCTX_PROC_POLL_RETX_TIMER_IND
[L2LMACTX] Ignore L2LMACTX_L2HRLCTX_PROC_POLL_RETX_TIMER_IND
[L2LMACTX][WARNING] PrevBo(%d) < DiscardSize:(%d)
[L2LMACTX] Updatae BO for PATH_CHANGE DiscardSize:%d, PrevBo:%d, Bo:%d
[L2LMACTX] L2_L2LMACTX_RESET_CNF MacEntity[%d]
[L2LMACTX]L2_L2LMACTX_CONFIG_CNF
[L2LMACTX] L2LMACTX_L2_CONFIG_REQ OpMode[%d]
[L2] Sending L2HRLCTX_L2LMACTX_RELEASE_BY_CONFIG_REQ_T Fail!
[L2LMACTX] L2HRLCTX_L2LMACTX_RELEASE_BY_CONFIG_REQ
[L2LMACTX] L2_L2LMACTX_CONFIG_CNF
[L2LMACTX] L2LMACTX_L2_RECOMMENDED_BIT_RATE_IND : Type[%d] Dir[%d] Bitrate[%d]
[L2LMACTX] L2LMACTX_L2_RESET_REQ : MacEntity[%d] ResetCause[%d]
[L2LMACTX] L2LMACTXPROXY_L2LMACTX_RESET_REQ
[L2LMACTX][E] CCIDX[%d] HID[%d]
[L2LMACTX] ULGrant Pause[%d] L1[%d/%d] PHY[%d/%d] SlotSz/CC/HID[0x%X] EarlyPause[%d]
[L2LMACTX][E] L2LMACTXENC_L2LMACTX_ENCODE_IND_T - AllocMsg Fail EncIdx[%d]
[L2LMACTX][E] L2LMACTXENC_L2LMACTX_ENCODE_IND_T - SendMsg Fail EncIdx[%d]
[L2LMACTX][E] L2LMACTXPROXY_L2LMACTX_TIMER_REQ_T - AllocMsg Fail
[L2LMACTX][E] L2LMACTXPROXY_L2LMACTX_TIMER_REQ_T - SendMsg Fail
[L2LMACTX][E] L2LMACTXPROXY_L2LMACTX_TIMER_REQ_T - SendMsg Fail
[L2LMACTX][E] L2LMACTX_L2LMACTXPROXY_TIMER_EXPIRE_IND_Handler [%d]
[L2LMACTX] L2LMACTX_ProcDmaDone : LcId(%d), StartPos(%d), EndPos(%d)
[L2LMACTX][E] L2HRLCRETX_L2LMACTX_DMA_DONE_IND_T - AllocMsg Fail
[L2LMACTX][E] L2HRLCRETX_L2LMACTX_DMA_DONE_IND_T - SendMsg Fail
[E] Full ULGrant msg WD[%d] RD[%d]
[E] Full ULEnc msg WD[%d] RD[%d]
PUCCH-SR enabled
PUCCH-SR disabled
LTE PHR disabled
LTE PHR enabled
