StartupInit: %d Failed
Create: No Timer available(%s,%d)
TimId(%d) created(%d/%d)(%s,%d)
Start: TimID(%d) deleted(%s,%d)
Start: TimID(%d) running(%s,%d)
Start: TimID(%u) duration(%d)(%s,%d)
Start: Failed to start TimID(%u)(%s,%d)
Start: Invalid TimId(%d)(%d)(%s,%d)
Stop: Invalid TimId(%d)(%s,%d)
Stop TimId(%d)(%s,%d)
Stop: TimId(%d) Stop Fail(%s,%d)
Stop: TimId(%d) deleted(%s,%d)
Stop: TimId(%d) Inactive(%s,%d)
Stop: TimId(%d) Invalid state(%d)(%s,%d)
BDA_HandleTimerExpiry: Unexpected TimerId(%d)
