[NR IPC] PHY_L1C_IPC_IF_TEST_IND, core(%d), cmd(%d)
[NR IPC] PHY_L1C_LCPU_INIT_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d), NrStatus(%d), StackId(%d)/CellGroup(%d)/PcellCc(%d)
[NR IPC] PHY_L1C_LCPU_INIT_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d), NrStatus(%d), StackId(%d)/CellGroup(%d)/PcellCc(%d)
(I)Received CcInfoBitmap Table in HEX (CC_Idx/Processor_Idx/Demod_Idx) 0:(0x%X), 1:(0x%X), 2:(0x%X), 3:(0x%X), 4:(0x%X), 5:(0x%X), 6:(0x%X)
(I)Received CcInfoBitmap Table in HEX (CC_Idx/Processor_Idx/Demod_Idx) 7:(0x%X), 8:(0x%X)
(F)Fail to update CC Info Table
(I)CC Index mapping info of My processor: MyProcessor(%d) cc_offset(0)->%d, cc_offset(1)->%d GetNrCcOn_Bitmap:0x%x
[NR IPC] L1C_PHY_LCPU_INIT_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d)
(F)Error in SetShmInfo: ShmIndex%d
[MDFS]LcpuInitReq, MdfsNrFlag(%d)
[NR IPC] PHY_L1C_LCPU_INIT_REQ(background) start, CC1_PER_PROC only cc_idx(%d)
[NR IPC] PHY_L1C_LCPU_INIT_REQ(background) end ccidx:%d cc_offset:%d Msg.MsgHdr.CcIdx:%d
[NR IPC] PHY_L1C_LCPU_RELEASE_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] IPC_NR_STATUS_IND_REQ Initialize(to LTE), BM_SrcCcForCnfMsg(%d)
[NR IPC] PHY_L1C_LCPU_STORE_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_LCPU_RESTORE_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_CELLGROUP_COMMON_CONFIG_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] L1C_PHY_CELLGROUP_COMMON_CONFIG_CNF, BM_SrcCcForCnfMsg(%d) BM_StackId(%d) BM_CellGroupId(%d)
[NR IPC] NR_ServingCellConfig_csi_MeasConfig is OFF
[DEBUG] SysParamChangeReqToProc: cc_offset(%d) CMD_INFO(%d) EVENT_INFO(%d) changeval(%d) isRestore(%d)
[NR IPC] PHY_L1C_CELLGROUP_PCELL_CONFIG_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] L1C_PHY_CELLGROUP_PCELL_CONFIG_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d)
[NR IPC] PHY_L1C_CELLGROUP_SCELL_CONFIG_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_SCELL_ACTDEACT_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] Force to change BW from over NUM_NR_SYS_BW ->(%d)
[NR IPC] PHY_L1C_OHC_MAX_TX_ANT_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
=====[NR_IPC]===== PHY_L1C_OHC_MAX_TX_ANT_REQ: CcIndex(%d), MsgId(%d)
[NR IPC] PHY_L1C_OHC_SCC_CQI0_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d), BM_SrcCcForCnfMsg %d
[NR IPC] PHY_L1C_SIB1_PCELL_CONFIG_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] L1C_PHY_SIB1_PCELL_CONFIG_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d)
[NR IPC] PHY_L1C_TDP_CONFIG_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_RXMODE_CHANGE_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_DATA_INACTIVE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_UL_ACTIVATION_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] skip carrierFreqUL=%d, carrierBandwidthUL = %d
[NR IPC] PHY_L1C_TX_SWAP_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_DL_NTM_MEASURE, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] IPC_NR_GAP_CTRL_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L2_MAC_RESET_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[MDFS]MacResetInd, Exception OFF, MdfsNrFlag(%d)
[NR IPC] PHY_L2_MAC_RACH_CONTROL_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] IPC_NR_RNTI_CONTROL_IND_t, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_PHY_RNTI_CFG_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_PHY_RACH_TX_INFO_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_PHY_RA_CrStateUpdate_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_PHY_RA_CFG_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_PHY_RA_CrStateReport_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_PHY_RA_CrStateReport_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_PHY_SPS_CLEAR_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L2_TA_CONTROL_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L2_TA_Timer_Ind, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_DRX_CMD_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_CHECK_TIME_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L2_PUCCH_SPATIAL_REL_ACT_DEACT_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L2_SP_SRS_ACT_DEACT_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L2_SP_CSIRS_CSIIM_ACT_DEACT_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L2_A_CSI_TRG_SUBSET_SUBSEL_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L2_PDSCH_TCI_STATES_ACT_DEACT_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L2_PDCCH_TCI_STATE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L2_PUCCH_SRS_RELEASE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L2_UE_BEAMLOCK_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_MIB_ACQ_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_QSLEEP_CTRL_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_SYS_PARAM_CHANGE_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_BWP_CHANGE_DONE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_SIB1_ACQ_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] L1C_PHY_SIB1_ACQ_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d)
[NR IPC] PHY_L1C_SIBX_ACQ_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] L1C_PHY_SIBX_ACQ_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d)
[NR IPC] PHY_L1C_MEAS_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_MTC_INFO_IND, FreqRange(%d) RsType(%d) SmtcSfn(%d) RxBeamIdx(%d) smtc_duration(%d) ssbbit[0/1](0x%x/0x%x)
[NR IPC] NrRcvSelfIpcHndlr_MtcInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_DRX_CFG_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_DRX_WAKEUP_INIT_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_PHY_NR_LTE_TXPOWER_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_SAR_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_NTM_MODE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_NTM_SET_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_PHY_TEST_MODE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_TMU_CTRL_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_VONR_STATUS_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR NTM] NrRcvSelfIpcHndlr_NtmMeasureReport: PHY_PHY_NTM_MEASURE_REPORT
[NR NTM] NrRcvSelfIpcHndlr_NtmMeasureReport: cc_offset = %d cc_idx = %d TARGET_CC_BITMAP.cc_idx = 0x%x,
[NR NTM] =====[NR_IPC]===== PHY_PHY_NTM_MEASURE_REPORT: CcIndex(%d), MsgId(%d)
=====[NR_IPC_SELF]===== (RCV) PHY_PHY_UPDATE_CC_TPUT_RATIO_IND: CcIndex(%d), MsgId(%d)
[NR IPC] PHY_PHY_ServingSSBChangeInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_PHY_ThermalLevelMeasure, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d), level(%d)
[NR IPC] PHY_L1C_STORE_PHY_CONFIG_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d), validflag(%d)
[NR IPC] L1C_PHY_STORE_PHY_CONFIG_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d)
[NR IPC] PHY_L1C_RESTORE_PCELL_PHY_CONFIG_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d) validflag_bmp(%d)
[NR IPC] L1C_PHY_RESTORE_PCELL_PHY_CONFIG_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d)
[MDFS]FR2 NrPhyRestorePcellConfigCnf, DFS Exception ON, MdfsNrFlag(%d)
[NR IPC] PHY_L1C_TX_SUSPEND_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_TX_RESUME_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_CONN_PRIO_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_PHY_RESUME_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_SSB_PATHCTRL_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d), Cmd : %d
[NR IPC] PHY_L1C_NR_EVENT_REPORT_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d), Type(%d)
Error in NrRcvIpcHndlr_NrEventReportReq: type(%d)
[NR IPC] L1C_PHY_NR_EVENT_REPORT_CNF, BM_SrcCcForCnfMsg(%d) BM_StackId(%d) BM_CellGroupId(%d)
[NR IPC] PHY_PHY_RACH_ASLOT_INFO2HBF_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_PHY_PCELL_SSB_IDX_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_PHY_LCPU_RELEASE_READY, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] L1C_PHY_LCPU_RELEASE_CNF, BM_SrcCcForCnfMsg(%d), BM_StackId(%d), BM_CellGroupId(%d)
[NR IPC] IPC_NR_STATUS_IND_REQ Release (to LTE), BM_SrcCcForCnfMsg(%d)
[MDFS]LcpuRelease_FR1, Exception OFF, MdfsNrFlag(%d)
[MDFS]LcpuRelease_FR2, Exception OFF, MdfsNrFlag(%d)
[NR IPC] releaseReady clear Ccinfo coreID:A%d cc:%d ccbitmap:0x%x
=====[NR_IPC_SELF]===== (RCV) PHY_PHY_NR_HBUF_UPDATE_REQ: MsgId(%d)
LTE Request MIF Boosting PHY_MIF_CONTROL_IND
[NR IPC] PHY_PHY_BWP_SWITCHING_CTRL_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_PHY_BWP_TIMER_STOP_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_PHY_CE_SCRAMBSEQ_CALC_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_PHY_CCH_RECONFIG_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_DciLengthCalculationInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_HashCalculationInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
=====[NR_IPC_SELF]===== NrRcvSelfIpcHndlr_MeasDoneInd, cc_idx: %d
[NR IPC] NrRcvSelfIpcHndlr_SysParamchgCfgdone, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_ScellStatusUpdateInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_PrachStartInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_PrachTransInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_ScellSlotConfigInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_PostProcSysParamChangeInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_PostProcScellConfigInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_PostProcScellActInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_StrSettlingInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_PLL_JITTER_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvIpcHndlr_NrMeasModeCtrlReq, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_NTM_ETSM_DISABLE_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_L1C_NTM_DPS_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_SibxSchedChange, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_PagingTimerCtrl, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_PHY_CalStartN0, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_SpsSchedulerReq, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_SpsSchedulerReq, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_PagingDrxCnfInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_SiDrxCnf, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_PHY_OTHER_CDRX_TIME_REPORT, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_TciSsbMappingInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_Cdrx_storeInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] PHY_PHY_SSB_PATHCTRL_IND, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_MdSwitchInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvSelfIpcHndlr_ClAitStartInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
###[TSIC][NR IPC] NrRcvIpcHndlr_TsicReq, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] SW_RESET NrRcvSelfIpcHndlr_SwResetInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] SW_RESET PHY_PHY_LTE_EVENT_REPORT_REQ, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
[NR IPC] NrRcvIpcHndlr_NrMonitorInd, coreID(%d), TargetCCinfoBitmap: cc_idx(%d), processor_idx(%d), hw_demod_idx(%d)
