SMPF Timer(m_pTimer) null. (0x%x)
SMPF Timer invalid SrcType req on create. (0x%x, SrcType:%u)
SMPF Timer Created. (0x%x)
FT is deleting. no need remove expired timer message
SMPF Timer Stop requested on ISR context. (0x%x)
SMPF Timer State(After Stop): %u->%u. (0x%x)
SMPF Timer Warning: Start on other FT. (0x%x)
SMPF Timer no operation with 0 repetiton (0x%x)
SMPF Timer Start is requested on ISR context. (0x%x)
SMPF Timer Started. (0x%x), (%u->%u), Duration = %u, IsUs = %u, pPara = 0x%x, NumRepeat = %u
SMPF Timer State(Before Delete): %u. (0x%x, 0x%x)
SMPF Timer(Context) null. (0x%x)
SMPF Timer(Context) null. (0x%x)
Error!! SMPF Timer SetUsRunDuration Failed. (0x%x, ostimer:0x%x)
Error!! SMPF Timer CalculateExpiryTime Failed. (0x%x, ostimer:0x%x)
SMPF Timer(MSG) Created. (0x%x)
SMPF Timer(CB) Created. (0x%x)
SMPF Timer(ISR) Created. (0x%x)
SMPF Timer State(Before Delete): %u. (0x%x)
call back timer test function!!!!!!!!!!!!!!!!!!!!!!!!
