GTimeSetTcuFrameCnt : tcu(%d) gcnt(%d)
Adjusted Irat fn (%d)
[GTimeSub] Prev FN(%d) TO(%d) / CUR FN(%d) TO(%d)
[GTimeCmp] Prev FN(%d) TO(%d) / CUR FN(%d) TO(%d)
[GTimeCmp] Diff FN (%d) TO (%d) Result (%d)
