3GT_RTG REGISTER SETTING is DONE
DBG SPI TX : [0x141 : 0x%X] [0x142 : 0x%X] [0x157 : 0x%X] [DBG_TRX_CON_SEL 0x%X] [RFD_TS_EN_BITMAP 0x%X] [RFD_TTX_SFR_CNT_LAT 0x%X]
DBG RFD TX : [EOT_ERROR 0x%X] [CRC_ERROR 0x%X] [DMIXER_TONE 0x%X] [TXF_IN_SWAP 0x%X] [TXF_OUT_SWAP 0x%X] [TRX_SW 0x%X] [TRX_OV_MODE 0x%X]
[HALRFCTL_3G][WARNING]NullFunc()!!
