[HALSYSTIME3GC] SetGapPosition: GAP_T_POS_CDMA_0(0x%X) GAP_T_POS_CDMA_1(0x%X) GAP_T_POS_CDMA_2(0x%X) GAP_T_POS_CDMA_3(0x%X) GAP_T_POS_CDMA_4(0x%X) GAP_T_POS_CDMA_5(0x%X)
[HALSYSTIME3GC] SetIntrPosition: INT_POS_CTRL_0(0x%X) INT_POS_CTRL_1(0x%X) INT_POS_CTRL_2(0x%X) INT_POS_CTRL_3(0x%X)
[HALSYSTIME3GC] GetSyncTime: systime_h(0x%x) systime_l(0x%x) sync_frame(%u) slot(%u) sync_chip(%u) chipx8(%u)
[HALSYSTIME3GC] GetSyncTime: systime_h(0x%x) systime_l(0x%x) slot(%u) sync_chip(%u) chipx8(%u)
[HALSYSTIME3GC] GetSyncTime: Wrong Rat(%d)
[HALSYSTIME3GC] GetRefSyncTime: systime_h(0x%x) systime_l(0x%x) sync_frame(%u) slot(%u) sync_chip(%u) chipx8(%u)
[HALSYSTIME3GC] GetRefSyncTime: systime_h(0x%x) systime_l(0x%x) slot(%u) sync_chip(%u) chipx8(%u)
[HALSYSTIME3GC] GetRefSyncTime: Wrong Rat(%d)
[HALSYSTIME3GC] GetLatchSyncTime: systime_h(0x%x) systime_l(0x%x) sync_frame(%u) slot(%u) sync_chip(%u) chipx8(%u)
[HALSYSTIME3GC] GetLatchSyncTime: systime_h(0x%x) systime_l(0x%x) slot(%u) sync_chip(%u) chipx8(%u)
[HALSYSTIME3GC] GetLatchSyncTime: Wrong Rat(%d)
[HALSYSTIME3GC] GetSleepSyncTime: systime_h(0x%x) systime_l(0x%x) sync_frame(%u) slot(%u) sync_chip(%u) chipx8(%u)
[HALSYSTIME3GC] GetSleepSyncTime: systime_h(0x%x) systime_l(0x%x) slot(%u) sync_chip(%u) chipx8(%u)
[HALSYSTIME3GC] GetSleepSyncTime: Wrong Rat(%d)
[HALSYSTIME3GC] GetPcgTime: pcg_chip(%u) pcg(%u) pcg_frame(%u)
[HALSYSTIME3GC] GetPcgTime: Wrong Rat(%d)
[HALSYSTIME3GC] GetRefPcgTime: pcg_chip(%u) pcg(%u) pcg_frame(%u)
[HALSYSTIME3GC] GetRefPcgTime: Wrong Rat(%d)
[HALSYSTIME3GC] StartGap: start_tick_enable(%u) end_tick_enable(%u)
[HALSYSTIME3GC] TxTmCtrl0UpdConfig: TX_TM_CTRL_EVDO_0(0x%x)
[HALSYSTIME3GC] TxTmCtrl1UpdConfig: TX_TM_CTRL_EVDO_1(0x%x)
[HALSYSTIME3GC] SetTimingMeas: CDMA_IRAT_TMEAS_SEL(0x%x)
[SLEEP3GC] Invalid rat type : %d
[HALSYSTIME3GC] Try to latch *****
[HALSYSTIME3GC] SetTxTmDeltaSyncTime: systime_h(0x%x) systime_l(0x%x) sync_frame(%u) slot(%u) sync_chip(%u) chipx8(%u)
[HALSYSTIME3GC] SetTxTmDeltaSyncTime: systime_h(0x%x) systime_l(0x%x) slot(%u) sync_chip(%u) chipx8(%u)
[HALSYSTIME3GC] SetTxTmDeltaSyncTime: Wrong Rat(%d)
[HALSYSTIME3GC] SetTxTmDeltaPcgTime: pcg_chip(%u) pcg(%u) pcg_frame(%u)
[HALSYSTIME3GC] SetTxTmDeltaPcgTime: Wrong Rat(%d)
[HALSYSTIME3GC] LoadTxTmDeltaTime: Wrong Rat(%d)
[HALSYSTIME3GC] LoadTxTmDeltaTime: enable(%d)
[HALSYSTIME3GC] InitTxTm: Wrong Rat(%d)
[HALSYSTIME3GC] InitTxTm: enable(%d)
[HALSYSTIME3GC] SetTxTmTracking: Wrong Rat(%d)
[HALSYSTIME3GC] SetTxTmTracking: TX_TM_CTRL_ONEX_0(0x%x) TX_TM_CTRL_EVDO_1(0x%x)
[HALSYSTIME3GC] SetTxTmTrackingPeriod: Wrong Rat(%d)
[HALSYSTIME3GC] SetTxTmTrackingPeriod: TX_TM_CTRL_ONEX_0(0x%x) TX_TM_CTRL_EVDO_1(0x%x)
[HALSYSTIME3GC] GetUrtgFrame: Wrong Rat(%d)
[HALSYSTIME3GC] GetUrtgFrame: URTG_3GD_CFN_MON_H(0x%x) URTG_3GD_CFN_MON_L(0x%x)
[HALSYSTIME3GC] SetRefDeltaSyncTime: systime_h(0x%x) systime_l(0x%x) sync_frame(%u) slot(%u) sync_chip(%u) chipx8(%u)
[HALSYSTIME3GC] SetRefDeltaSyncTime: systime_h(0x%x) systime_l(0x%x) slot(%u) sync_chip(%u) chipx8(%u)
[HALSYSTIME3GC] SetRefDeltaSyncTime: Wrong Rat(%d)
[HALSYSTIME3GC] SetRefDeltaPcgTime: pcg_chip(%u) pcg(%u) pcg_frame(%u)
[HALSYSTIME3GC] SetRefDeltaPcgTime: Wrong Rat(%d)
[HALSYSTIME3GC] SetRefCntCtrl: Wrong Rat(%d)
[HALSYSTIME3GC] SetRefCntCtrl: refcnt_ctrl_mode(0x%x)
[HALSYSTIME3GC] SetAGPSCtrl: CDMA_AGPS_CTRL(0x%x) REFCNT_CTRL_EVDO(0x%x)
[HALSYST_3GC][WARNING]NullFunc()!!
