[INFRA] SetDfsModeForNonRtBlock: rat(%d), clock_mode(%d)
[INFRA] SetDemodComSharedMemClk: rat(%d)
[INFRA] HALINFRA_SetTurboClkSel: rat(%d)
[INFRA] HALINFRA_SetLVDClk: rat(%d)
[INFRA] HALINFRA_SetTbArbiterClk: rat(%d)
[INFRA] HALINFRA_SetSbSharedMemClk: rat(%d)
[INFRA] SetModemRat(%d): rat(%d)
[INFRA] SwReset(%d): rst(%08x, %08x, %08x) clkRegSize(%d)byte
[INFRA] SetDynClkOnOff(%d): on(%d), clk(%08x, %08x, %08x) clkRegSize(%d)byte
[INFRA] SwReset(%d): rst(%08x, %08x, %08x)
[INFRA] SetSwClkOnOff(%d): on(%d), clk(%08x, %08x, %08x)
[INFRA] SetQchDynClkOnOff(%d), mdm_pd(%d)
[DEBUG][INFRA] Skip RegSliceClkOnOff cause clk didn't change read(%08x) == write(%08x)
[INFRA] SetRegSliceClkOnOff(%d): on(%d), clk(%08x), add(%08x), reg_clk(%08x)
[INFRA] SetDemodComSearcherEn: enable(%d)
[INFRA] HALINFRA_SetScalingClkSel(%d), mdm_pd(%d)
[INFRA] HALINFRA_SetRakeClk: rat(%d)
[INFRA] SubInt0Hndlr: Handler is not registered(%d)
[INFRA] SubInt1Hndlr: Handler is not registered(%d)
[INFRA] SubInt2Hndlr: Handler is not registered(%d)
[INFRA] SubInt3Hndlr: Handler is not registered(%d)
[INFRA] SubInt4Hndlr: Handler is not registered(%d)
[INFRA] SubInt5Hndlr: Handler is not registered(%d)
[INFRA] SubInt6Hndlr: Handler is not registered(%d)
[INFRA] SubInt7Hndlr: Handler is not registered(%d)
[INFRA] SubInt8Hndlr: Handler is not registered(%d)
[INFRA] SubInt9Hndlr: Handler is not registered(%d)
[INFRA] SubInt10Hndlr: Handler is not registered(%d)
[INFRA] SubInt11Hndlr: Handler is not registered(%d)
[INFRA] SubInt12Hndlr: Handler is not registered(%d)
[INFRA] SubInt13Hndlr: Handler is not registered(%d)
[INFRA] SubInt14Hndlr: Handler is not registered(%d)
[INFRA] SubInt15Hndlr: Handler is not registered(%d)
[INFRA] SubInt16Hndlr: Handler is not registered(%d)
[INFRA] SubInt17Hndlr: Handler is not registered(%d)
[INFRA] SubInt18Hndlr: Handler is not registered(%d)
[INFRA] SubInt19Hndlr: Handler is not registered(%d)
[INFRA] SubInt20Hndlr: Handler is not registered(%d)
[INFRA] SubInt21Hndlr: Handler is not registered(%d)
[INFRA] SubInt22Hndlr: Handler is not registered(%d)
[INFRA] SubInt23Hndlr: Handler is not registered(%d)
[INFRA] SubInt24Hndlr: Handler is not registered(%d)
[INFRA] SubInt25Hndlr: Handler is not registered(%d)
[INFRA] SubInt26Hndlr: Handler is not registered(%d)
[INFRA] SubInt27Hndlr: Handler is not registered(%d)
[INFRA] SubInt28Hndlr: Handler is not registered(%d)
[INFRA] SubInt29Hndlr: Handler is not registered(%d)
[INFRA] SubInt30Hndlr: Handler is not registered(%d)
[INFRA] SubInt31Hndlr: Handler is not registered(%d)
[INFRA] SubInt32Hndlr: Handler is not registered(%d)
[INFRA] SubInt33Hndlr: Handler is not registered(%d)
[INFRA] SubInt34Hndlr: Handler is not registered(%d)
[INFRA] SubInt35Hndlr: Handler is not registered(%d)
[INFRA] SubInt36Hndlr: Handler is not registered(%d)
[INFRA] SubInt37Hndlr: Handler is not registered(%d)
[INFRA] SubInt38Hndlr: Handler is not registered(%d)
[INFRA] SubInt39Hndlr: Handler is not registered(%d)
[INFRA] SubInt40Hndlr: Handler is not registered(%d)
[INFRA] SubInt41Hndlr: Handler is not registered(%d)
[INFRA] SubInt42Hndlr: Handler is HALDMov_DefaultIntHandler(%d) => PEND(0x%x), EN(0x%x), MASK(0x%x)
[INFRA] SubInt42Hndlr: Handler is not registered(%d)
[INFRA] SubInt43Hndlr: Handler is not registered(%d)
[INFRA] SubInt44Hndlr: Handler is not registered(%d)
[INFRA] SubInt45Hndlr: Handler is not registered(%d)
[INFRA] SubInt46Hndlr: Handler is not registered(%d)
[INFRA] SubInt47Hndlr: Handler is not registered(%d)
[INFRA] SubInt48Hndlr: Handler is not registered(%d)
[INFRA] SubInt49Hndlr: Handler is not registered(%d)
[INFRA] SubInt50Hndlr: Handler is not registered(%d)
[INFRA] SubInt51Hndlr: Handler is not registered(%d)
[INFRA] SubInt52Hndlr: Handler is not registered(%d)
[INFRA] SubInt53Hndlr: Handler is not registered(%d)
[INFRA] SubInt54Hndlr: Handler is not registered(%d)
[INFRA] SubInt55Hndlr: Handler is not registered(%d)
[INFRA] SubInt56Hndlr: Handler is not registered(%d)
[INFRA] SubInt57Hndlr: Handler is not registered(%d)
[INFRA] DisableRatIntrs: rat(%d), active(%d)
[INFRA] frontTx2gClk_0(0x%x) frontTx2gClk_1(0x%x) frontRxClk_0(0x%x) frontRxClk_1(0x%x) symbprocClk_0(0x%x) turboClk(0x%x)
[INFRA] front_modem_sel %d, mbus_demod_3g_modem_sel %d, rear_modem_sel %d, turbo_modem_sel %d
[INFRA] CheckLVDStatus 1: LVD_STATUS_MON(0x%x), CCH_DEC_STATE_MON(0x%x), CCH_CLOCK_ON(0x%x), SP_CCH_3G_LVD_STATUS(0x%x)
[INFRA] CheckLVDStatus 2: SW_CLK_ON(0x%x), on_off(%d)
[INFRA] CheckLVDStatus 3: LVD_STATUS_MON(0x%x), CCH_DEC_STATE_MON(0x%x), CCH_CLOCK_ON(0x%x), SP_CCH_3G_LVD_STATUS(0x%x)
[INFRA] CheckLVDStatus : LVD_STATUS_0(0x%x), LVD_STATUS_1(0x%x), LVD_STATUS_2(0x%x), LVD_STATUS_3(0x%x), LVD_3G2G_CLK_SEL_DIFF(0x%x)
[INFRA] DYN_CLK_OFF : FDBUF_CE_M->0(0x%x), DN_CE_S->1(0x%x), POSTCE_MS->0(0x%x)
[INFRA][SW_WA] DYN_CLK_OFF : SD_M->(0x%x)
[INFRA] No register interrupt for sub interrupt
[INFRA] There is no LCPU response for the C2D interrupt
[INFRA] LCPU has not been freed from C2P interrupt
infraRearSettingForTurbo: TURBO_CLK_SEL0 0x%08X, TURBO_CLK_SEL1 0x%08X, TB_ARBITER_CLK_SEL 0x%08X, SW_CLK_ON 0x%08X, DYN_CLK_ON_EN 0x%08X, MODEM_SEL 0x%08X
HALINFRA_DisableLmacTxIntr, ActiveRatInfo %d
[HALINFRA][WARNING]NullFunc()!!
