[HALRFCTRL3GC] StartRfInterrupt: CTRL_STATE(0x%X)
[HALRFCTRL3GC] SetRxGainUpdateMode: MODE(%u)
[HALRFCTRL3GC] SetIratMuxGpsSel: IRAT_MUX_GPS_SEL(0x%X)
[HALRFCTRL3GC] SetGainActiveRat: RX_GAIN_ACTIVE_RAT(0x%X)
[HALRFCTL_3GC][WARNING]NullFunc()!!
