Invalid RAT for CheckSpurFreqNV
enabledSpurFreqNV[%d] %d
HALRXF_GetFmixerForSpurFreq : %d unsupported BW for spurFreq
Fmixer(%d) = sFreq(%u)-cFreq(%u)+freqOffset(%d)
Fmixer %d
HALRXF_SetTRFCC Wrong cc %d
cc %d dcrSel %d lbw0 %d lbw1 %d Fmixer0 0x%x Fmixer1 0x%x Fmixer2 0x%x
HALRXF_GetBWHz : %d unsupported BW for spurFreq
cFreq %u bw %d dcrSel %d freqOffset %d binNum[%d] %d
pCFreq[0] %u pBW[0] %d
pCFreq[1] %u pBW[1] %d
Invalid RAT for CheckSpurFreqNV
nvFreq %u cFreq %u distance %d bwHz %d
numOfNotch %d lbw %d rxChain 0x%x
freqOffsetRange %d step %d
bestTRFFreq(%u) = spurFreq[0](%u)+ bestTestOffset(%d) bestSirTRF %d
cnt %d testTRFFreq(%u)=spurFreq[0](%u)+testOffset(%d) sirTRF %d
bestTRFFreq(%u) bestSirTRF %d
TRF pass: numOfNotch[%d] %d
[HALRXF] GetRxfDb: rat/db_idx(%d/%d), Called by '%s()'
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SwapIQ: RFD_DCR_DATA_SEL_IQ_SEL(0x%X)
[HALRXF] SwapIQ: rat/db_idx(%d/%d), dcr(%d), enable(%d)
[SOC-84741] HALEXP_GetTestSimStatus = TRUE, pal_ERegId_NASU_DNS_QUERY_BLOCK [%d] userreq_gcfmode [%d]
[HALRXF] InitRxFilter: Wrong rat/db_idx(%d/%d)
[HALRXF] InitRxFilter: rat/db_idx(%d/%d), sub6_onoff(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetPgcRamTable: RXF_PGC_MODE[%d](0x%X)
[HALRXF] SetPgcRamTable: length %d PGC_RAM_ADDR 0x%X gain_word[%d][%d] 0x%0X
pgc_addr_rf[%d] 0x%x
[HALRXF] SetPgcRamTable: Wrong rat/db_idx(%d/%d)
[HALRXF] SetPgcRamTable: RAM%d[%d] = WR(0x%x, 0x%x), RD(0x%x, 0x%x)
[HALRXF] SetPgcRamTable: d2d_pgc_sel(%d), band(%d -> %d), pgc_sel(%d), ram(%d, %d), size(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
agc_sel %d agc_pgc[0] 0x%x agc_pgc[1] 0x%x pgc_addr_rf 0x%x
[HALRXF] SetPgcRamSel: RXF_AGC_PGC_ANT[%d](0x%X), RXF_AGD_PGC_ANT[%d](0x%X)
[HALRXF] SetPgcRamSel: dcr(%d),agc(%d) pgc(%d), Pgc_ram_sel(%d, %d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetAgcHys: HYS_RISE_ANT[%d](0x%X)
[HALRXF] SetAgcHys: HYS_FALL_ANT[%d](0x%X)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetAgcHys: ANT_INDEX(0x%X)
[HALRXF] SetAgcHys: Wrong rat/db_idx(%d/%d)
[HALRXF] SetAgcHys: dcr(%d), enable(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetAgcAntInput: Wrong rat/db_idx(%d/%d)
[HALRXF] SetAgcAntInput: avg_sel(%08x) avg_input(%08x, %08x)
[HALRXF] SetAgcAntInput: agc_ant_input(0x%08X, 0x%08X, 0x%08X, 0x%08X, 0x%08X)
[HALRXF] SetAgcAntInput: rx_mode(%d), rf(%d), mxr(%d), bw(%d)
[HALRXF] SetInterpolator: Wrong rat/db_idx(%d/%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetFbRx: fbDumpA(%X), fbDumpAccL(%X), fbAccL1(%X), fbAccL2(%X)
[HALRXF] SetFbRx: rxf_db->rf_path = %d, RxfInfo.dcr_sel = %d, rfd_sampling_rate = 0x%x, fbrxSamplingRate = 0x%x, fbrxADC = 0x%x
[HALRXF] SetFbRx#2: RFD_FBRX_INPUT_SEL = 0x%x, RFD_FBRX_INOUT_SEL = 0x%x, RFD_OUT_DATA_SEL_F = 0x%x
[HALRXF] SetFbRx: Wrong rat/db_idx(%d/%d)
[HALRXF] SetFbRx: enable(%d), rf(%d), dcr(%d), mode(%x), bw(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetPowMeas: Wrong rat/db_idx(%d/%d)
[HALRXF] SetPowMeas: rat/db_idx(%d/%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetDif: dif(0x%X)
[HALRXF] SetModeSetChange dcr_sel(%d) dif_out_data_sel(0x%X)
[HALRXF] SetModeSetChange : FBRx path OUT_DATA LOCK
[HALRXF] SetModeSetChange FBRX feedbackread(0x%X) DVALID_FIFO_EN(0x%X 0x%X) DVALID_FIFO_STAT(0x%X)
[HALRXF] SetModeSetChange feedbackread(0x%X) DVALID_FIFO_EN(0x%X) DVALID_FIFO_STAT(0x%X)
###[NR_RXFILTER] SetModeSetChange: rfm_mxr_sel(%d), RFM_VALID(0x%X), MAR_OUTEN(0x%X)
###[NR_RXFILTER] SetModeSetChange[DEBUG]: rfm_mxr_sel(%d), DIF_MM_DVALID_CLK_SEL(0x%X)
###[NR_RXFILTER] SetModeSetChange: rfm_mxr_sel(%d), RFM_VALID(0x%X), MAR_OUTEN(0x%X)
[HALRXF] SetModeSetChange dcr_sel(%d), ratsamplingchanged(%d), sub6_onoff(%d)
[HALRXF] HALRXF_SetLPM : FRONT_RX is already off
[HALRXF] UsingCCNum cnt(%d), LPMSupportedCC(%d), IsLPM(%d)
[HALRXF] HALRXF_SetLPM : HALF -> FULL
[HALRXF] HALRXF_SetLPM : FULL -> HALF
[HALRXF] HALRXF_SetLPM : Keep current mode(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetGainSplitter: Wrong rat/db_idx(%d/%d)
[HALRXF] SetGainSplitter: dcr(%d), rx_mode(%d), GAIN_SPLITTER(%X)
[HALRXF] InitRatSamplingMode: Wrong rat/db_idx(%d/%d)
[HALRXF] SetRatSamplingMode: rat/db_idx(%d/%d), max_cc(%d), max_rfPath(%d), sub6_onoff(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] GetRatSamplingMode: Wrong rat/db_idx(%d/%d)
[HALRXF] GetRatSamplingMode: rat/db_idx(%d/%d), bw(%d), RatSamplingMode(0x%X)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetRatSamplingMode: RXF_RAT_SAMPLING_MODE[%d](0x%X), RFD_RXF_RAT_[%d](0x%X) ?= rfd_ccinfo(0x%X)
[HALRXF] SetRatSamplingMode: rat/db_idx(%d/%d), dcr_sel(%d), rx_mode(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetMixRatSamplingMode: Wrong rat/db_idx(%d/%d)
[HALRXF] SetMixRatSamplingMode: RXF_MIX_RAT_SAMPLING_MODE[%d](0x%X)
[HALRXF] SetMixRatSamplingMode: rat/db_idx(%d/%d), mxr_sel(%d), rx_mode(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetRxFilterOutput: RXF_FFT_INPUT_SEL_x.reg[%d](0x%X)
[HALRXF] SetRxFilterOutput: Wrong rat/db_idx(%d/%d)
[HALRXF] SetRxFilterOutput(CC%d): mxr(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetDcrSel: DCR_DATA_SEL/DSEL(0x%X, 0x%X), ADC_SEL/DSEL(0x%X, 0x%X), DCR_ADJUST_SET(0x%X, 0x%X)
[HALRXF] SetDcrSel: rf_path(%d), dcr(%d), rx_mode(%d), enable(%d), ant_swap_en(%d), rx_iq_swap(0x%x)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetAgcMode: RXF_AGC_MODE_SET_x_CC[%d](0x%X)
[HALRXF] AGC[ENABLE]: Wrong rat/db_idx(%d/%d)
[HALRXF] SetAgcMode: rat/db_idx(%d/%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] HALRXF_SetDVGADelayOffset: dvgaOffset(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetDVGAOffset: dvgaOffset(%d)
[HALRXF] SetDVGAMode: Wrong rat/db_idx(%d/%d)
[HALRXF] SetDVGAMode: dvgaOffset
[HALRXF] %s: Wrong %s(%d)
[HALRXF] GetMxrBw: Wrong rat/db_idx(%d/%d)
[HALRXF] GetMxrBw: bw(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetAGCUpdateRate: Wrong rat/db_idx(%d/%d)
[HALRXF] SetAGCUpdateRate: rat/db_idx(%d/%d)
[HALRXF] SetAGCAccLength: Wrong rat/db_idx(%d/%d)
[HALRXF] SetAGCAccLength: rat/db_idx(%d/%d)
[HALRXF] SetAGCLoopGain: Wrong rat/db_idx(%d/%d)
[HALRXF] SetAGCLoopGain: shift_k(0x%x)
[HALRXF] SetAGCRefOffset: Wrong rat/db_idx(%d/%d)
[HALRXF] SetAGCRefOffset: ref_offset(0x%x)
[HALRXF] SetClk245: RXF_CLK245_ON(0x%X)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetExtLnaMode: rf(%d), dcr(%d), j(%d), mode(%d), offset[0](%d), offset[1](%d), offset[2](%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetExtLnaModeOvr: rf(%d), dcr(%d), num(%d), ov(%d), wr(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetExtLnaHys: rf(%d), dcr(%d), num(%d), hys[0,1](%d), hys[2,3](%d), hys[4,5](%d)
[HALRXF] SetExtLnaTickMode: Wrong rat/db_idx(%d/%d)
[HALRXF] SetExtLnaTickMode: RXF_EXT_LNA_TICK_MODE_x.reg(0x%X)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] GetIqcCoefValue(%d): TAP(%d), I(%x), Q(%x)
[HALRXF] GetIqcCoefValue: rat/db_idx(%d/%d), iqc(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetIqcCoefValue: OV_ANT(%x), TAP(%d), I(%x), Q(%x)
[HALRXF] SetIqcCoefValue: OV_ANT(%x), TAP(%d), I(%x), Q(%x)
[HALRXF] SetIqcCoefValue: rat/db_idx(%d/%d), iqc(%d), coef[0](%d), coef[1](%d), coef[2](%d)
[HALRXF] CLOCK[INIT]: Wrong rat/db_idx(%d/%d)
[HALRXF] CLOCK[INIT]: rat/db_idx(%d/%d)
[HALRXF] OPERATION[INIT]: Wrong rat/db_idx(%d/%d)
[HALRXF] OPERATION[INIT]: rat/db_idx(%d/%d), sub6_onoff(%d)
[HALRXF] ConfigDVGA_Hys: Wrong rat/db_idx(%d/%d)
[HALRXF] SRRCF[INIT]: rat/db_idx(%d/%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SRRCF[ENABLE]: BYPASS(0x%X)
[HALRXF] SRRCF[ENABLE]: rat/db_idx(%d/%d), mxr_sel(%d), enable(%d), rx_mode(%d)
[HALRXF] DVGA[INIT]: Wrong rat/db_idx(%d/%d)
[HALRXF] DVGA[INIT]: rat/db_idx(%d/%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] DVGA[ENABLE]: BYPASS(0x%X)
[HALRXF] DVGA[ENABLE]: RXF_DVGA[%d].OFFSET(0x%X)
[HALRXF] DVGA[ENABLE]: RXF_DVGA[%d].OFFSET(0x%X)
[HALRXF] DVGA[ENABLE]: OFFSET_DELAY_OV(0x%X)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] DVGA[ENABLE]: rf_path(0x%X), OFFSET_TICK_MODE(0x%X), dvga_dly(0x%X)
[HALRXF] DVGA[ENABLE]: dcr_sel(%d), GAIN_INDEX(0x%X), GAIN_HYS_SEL(0x%X)
[HALRXF] DVGA[ENABLE]: Wrong rat/db_idx(%d/%d)
[HALRXF] DVGA[ENABLE]: rat/db_idx(%d/%d), mxr_sel(%d), enable(%d), bw(%d), rx_mode(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] ConfigDVGA_Hys: Wrong rat/db_idx(%d/%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetDvgaHys: GAIN_MAPPER(0x%X)
[HALRXF] SetDvgaHys: GAIN_INDEX_HYS_FALL (0x%X)
[HALRXF] SetDvgaHys: GAIN_INDEX_HYS_RISE (0x%X)
[HALRXF] SetDvgaHys: GAIN_INDEX_HYS_ENABLE_GAIN_LEVELMAPPER (0x%X)
[HALRXF] SetDvgaHys: enable(%d), hys(%d, %d, %d, %d, %d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] IQC[DISABLE]: Wrong rat/db_idx(%d/%d)
[HALRXF] IQC[DISABLE]: rat/db_idx(%d/%d), iqc_sel(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] IQC[INIT]: IQC_OPERATION_SET(0x%X)
[HALRXF] IQC[INIT]: IQC_OPERATION_SET(0x%X)
[HALRXF] IQC[INIT]: IQC_OPERATION_SET_CDMA(0x%X)
[HALRXF] IQC[INIT]: Wrong rat/db_idx(%d/%d)
[HALRXF] IQC[INIT]: rat/db_idx(%d/%d), iqc_sel(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] IQC[ENABLE]: IQC_OPERATION_SET_CC(0x%X)
[HALRXF] IQC[ENABLE]: IQC_OPERATION_SET_CC(0x%X)
[HALRXF] IQC[ENABLE]: IQC_OPERATION_SET_CDMA(0x%X)
[HALRXF] IQC[ENABLE]: Wrong rat/db_idx(%d/%d)
[HALRXF] IQC[ENABLE]: rat/db_idx(%d/%d), iqc_sel(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] IQC[OVR]: Wrong rat/db_idx(%d/%d)
[HALRXF] IQC[OVR]: rat/db_idx(%d/%d), iqc_sel(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] IQC[RESET]: IQC_OPERATION_SET_CC(0x%X)
[HALRXF] IQC[RESET]: IQC_OPERATION_SET_CDMA(0x%X)
[HALRXF] IQC[RESET]: Wrong rat/db_idx(%d/%d)
[HALRXF] IQC[RESET]: rat/db_idx(%d/%d), iqc_sel(%d)
[HALRXF] IQD[INIT]: Wrong rat/db_idx(%d/%d)
[HALRXF] IQD[INIT]: RFD_RXF_IQD_x(0x%X)
[HALRXF] IQD[INIT]: rat/db_idx(%d/%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] DCR[DISABLE]: Wrong rat/db_idx(%d/%d)
[HALRXF] DCR[DISABLE]: rat/db_idx(%d/%d), dcr_sel(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] DCR[INIT]: Wrong rat/db_idx(%d/%d)
[HALRXF] DCR[INIT]: rat/db_idx(%d/%d), dcr_sel(%d)
[HALRXF] DCR INPUT[INIT]: rat/db_idx(%d/%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] DCR[ENABLE]: RFD_DCR_OPERATION_SET_CC%d(0x%X)
[HALRXF] DCR[ENABLE]: Wrong rat/db_idx(%d/%d)
[HALRXF] DCR[ENABLE]: rat/db_idx(%d/%d), dcr_sel(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] DCR[OVR]: rat/db_idx(%d/%d), dcr_sel(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] DCR[RESET]: rat/db_idx(%d/%d), dcr_sel(%d)
[HALRXF] DCRAntOverride
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SyncDCF: RXF_SYNC_4G.MODE(%x), RXF_SYNC_4G.SCALING_BYPASS(%d), RXF_SYNC_AGC_SET.MODE(%x)
[HALRXF] SyncDCF: Worng rat/db_idx(%d/%d)
[HALRXF] SyncDCF: rat/db_idx(%d/%d), mxr(%d), mode(%d), bw(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] AGC[DISABLE]: rat/db_idx(%d/%d), mxr_sel(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] AGC[INIT]: Wrong rat/db_idx(%d/%d)
[HALRXF] AGC[INIT]: rat/db_idx(%d/%d), mxr_sel(%d), dcr_sel(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] AGC[ENABLE]: Wrong rat/db_idx(%d/%d)
[HALRXF] AGC[ENABLE]: rat/db_idx(%d/%d), mxr_sel(%d), dcr_sel(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] AGC[OV]: agc_value[0]: OV(0x%X), WR(0x%X), START(0x%X)
[HALRXF] AGC[OV]: agc_value[1]: OV(0x%X), WR(0x%X), START(0x%X)
[HALRXF] AGC[OV]: rat/db_idx(%d/%d), mxr_sel(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] AGC[RESET]: Wrong rat/db_idx(%d/%d)
[HALRXF] AGC[RESET]: rat/db_idx(%d/%d), mxr_sel(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] ConfigAGC_Hys: Wrong mode(%d)
[HALRXF] ConfigAGC_Hys: Wrong rat/db_idx(%d/%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] AGCAccReset: Wrong rat/db_idx(%d/%d)
[HALRXF] MIXER[INIT]: Wrong rat/db_idx(%d/%d)
[HALRXF] MIXER[INIT]: rat/db_idx(%d/%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] MIXER[ENABLE]: BYPASS(0x%X)
[HALRXF] MIXER[ENABLE]: RXF_MIXER_NEXT_x.reg(0x%08x)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] MIXER[ENABLE]: Wrong rat/db_idx(%d/%d)
[HALRXF] MIXER[ENABLE]: rf(%d), dcr(%d), mxr(%d), enable(%d), bw(%d), rx_mode(%x)
[HALRXF] ConfigExtLNA[ENABLE]: Wrong rat/db_idx(%d/%d)
[HALRXF] ConfigExtLNA_Hys: Wrong rat/db_idx(%d/%d)
[HALRXF] PEQ[INIT]: Worng rat/db_idx(%d/%d)
[HALRXF] PEQ[INIT]: rat/db_idx(%d/%d)
[HALRXF] TFR[INIT]: Worng rat/db_idx(%d/%d)
[HALRXF] TFR[INIT]: rat/db_idx(%d/%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] ConfigCDMA[INIT]: Worng rat/db_idx(%d/%d)
[HALRXF] ConfigCDMA[INIT]: rat/db_idx(%d/%d), rx_mode(%d)
[HALRXF] SetAgcCDMA: RXF_CDMA_AGC_3GC(0x%x)
[RXF] SetADC: rf(%d), mode(%d), bw(%d)
[RXF] GetMxrSelList: rf(%d), mxr(%d, %d), mode(%d)
[HALRXF_SetFbRx] RFD_FBRX_SAMPLING_MODE 0x%x, RFD_RXF_RAT_0 0x%x, RFD_RXF_RAT_5 0x%x, RFD_MPLL_CLK_SEL_CC0 0x%x, RFD_MPLL_CLK_SEL_CC5 0x%x, RFD_FBRX_DCR0 0x%x, RFD_FBRX_DCR1 0x%x
[HALRXF_SetFbRx] RFD_FBRX_AGC0 0x%x, RFD_FBRX_AGC1 0x%x, RFD_FBRX_INOUT_SEL 0x%x, RFD_FBRX_INPUT_SEL 0x%x, RFD_DCR_CON_5 0x%x, RFD_MPLL_CLK_SEL_CDMA 0x%x, FBRX_SAMPLING_MODE 0x%x
[ADC CC0] Dump MSpeedy = 0x%03x , 0x%08x
[ADC CC5] Dump MSpeedy = 0x%03x , 0x%08x
[ADC CC7] Dump MSpeedy = 0x%03x , 0x%08x
[HALRXF] %s: Wrong %s(%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetExtLnaMode: rf(%d),mode(%d), offset[0](%d), offset[1](%d), offset[2](%d)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] SetExtLnaHysfor3G: rf(%d), hys[0,1](%d), hys[2,3](%d), hys[4,5](%d)
[HALRXF] ReOrderFftInputSel: Rx mode(%d -> %d) mxr_sel(%d), output_sel(%d), FFT_INPUT_SEL(%x, %x)
[HALRXF] HALRXF_GetUsingCCNum: using_cc(%d) mxr_cc(%d) dcr_cc(%d) is_configured_slo(%d)
[HALRXF] MIXER[ENABLE]: RXF_MIXER_NEXT_x.reg(0x%08x)
[HALRXF] SetRatSamplingMode: RXF_RAT_SAMPLING_MODE[%d](0x%X), RFD_RXF_RAT_[%d](0x%X) ?= rfd_ccinfo(0x%X)
TRF cFreq == 0
trfBin[0] %d trfBin[1] %d
same dcrSel %d : trfBin[%d] %d
new dcrSel : trfBin[%d] %d
HALRXF_SetTRFSIR sirTRF %d
[HALRXF] %s: Wrong %s(%d)
[HALRXF] HALRXF_SetLinkChannel : rat/db_idx(%d/%d), dcr_sel(%d), sampling_mode(0x%02X), dif_out_data_sel(0x%X)
[HALRXF] %s: Wrong %s(%d)
[HALRXF] HALRXF_SetDValidRate: Abnormal argument - sampling_mode[0x%02X]
[HALRXF] HALRXF_SetDValidRate: Abnormal argument - rat[%d]
[HALRXF] HALRXF_SetDValidRate: Abnormal argument - sampling_mode[0x%04X]
[HALRXF] HALRXF_SetDValidRate: Abnormal argument - sampling_mode[%d]
[HALRXF] HALRXF_SetDValidRate : rat/db_idx(%d/%d), dcr_sel(%d), sampling_mode(0x%02X), dvalid_rate(0x%01X)
[HALRXF]FuncHead()!!
[HALRXF][WARNING]NullFunc()!!
[HALRXF]FuncTail()!!
