[SLEEP5G] InitSleep: MifWakeUpTime(%d)
[SLEEP5G][WARNING] EnableDrxIntr: Unexpected Intr(%d)
[SLEEP5G] EnableDrxIntr: Intr(%d)
[SLEEP5G][WARNING] DisableDrxIntr: Unexpected Intr(%d)
[SLEEP5G] DisableDrxIntr: Intr(%d), Pend(%d)
[SLEEP5G][WARNING] ClearDrxIntr: Unexpected Intr(%d)
[SLEEP5G] ClearDrxIntr: Intr(%d)
[SLEEP5G] ForceSwSysValidEnable: ReqSleep(%d), Status(0x%X), XfrRefCnt(0x%x)
[SLEEP5G] AbortSleep: ReqSleep(%d), Status(0x%X), SlpCnt(%d), Remained Time(%d)
[SLEEP5G] StartSleep: SleepTime(%d), Status(%d)
[SLEEP5G] SetOvrRcValue: OvrRcValue(%d), RefCnt(Ini: %d, Gat: %d)
[SLEEP5G] SetFreqErrAccPeriod: Enable(%d), Period(%d)
[SLEEP5G] UpdateSleepTime: SleepTime(%d) Remained Time(%d -> %d) SlpCtl(0x%x), SlpStatus(0x%x), SlpCnt(%d)
[HALSLEEP_5G][WARNING]NullFunc()!!
