[MDM] SetClockGating[DEBUG]: DfsEnabled(0x%x), CurClkRate(0x%x), LteSpecialMode(0x%x), NrSpecialMode(0x%x)
[MDM] SetClockGating[DEBUG]: DfsActMode(0x%x), PrevRateMode(0x%x), RateMode(0x%x), PrevRat(0x%x), Rat(0x%x), NumLteCc(0x%x), NumNrCc(0x%x)
[MDM] SetClockGating[DEBUG]: NumLteRxPath(0x%x), NumNrRxPath(0x%x), IsIrat(0x%x), PreRmode(0x%x)
[MDFS][WARNING] %s: Wrong %s(%d)
[MDFS][WARNING] %s: Wrong %s(%d)
[MDFS][WARNING] %s: Wrong %s(%d)
[MDFS][%d]UpdateRxMode: rat(%d), rxmode(%d)
[MDFS][WARNING] %s: Wrong %s(%d)
[MDFS][WARNING] %s: Wrong %s(%d)
[MDFS][WARNING] %s: Wrong %s(%d)
[MDFS][%d]ChangeMode: rat(%d), cc(%d), DfsMode(%d), DfsStep(0x%x)
[MDFS][WARNING] %s: Wrong %s(%d)
[MDFS][WARNING] %s: Wrong %s(%d)
[MDFS][%d]ModemDfsNv(%d), LogLev(%d)
[MDFS][WARNING]SetDfsInfor: LteSpecialMode is minus(-), set to Zero(0x0)
[MDFS][WARNING]SetDfsInfor: NrSpecialMode is minus(-), set to Zero(0x0)
[MDFS][%d]SetDfsInfor: Rat(%d => %d), ActMode(%d)[%s], startend(%d), Called by '%s()'
[MDFS][WARNING] %s: Wrong %s(%d)
[MDFS][WARNING] %s: Wrong %s(%d)
[MDFS][%d]UpdateBw: rat(%d), bw(%d), DfsMode(%d), DfsStep(0x%x)
[MDFS]SetDfsInfoToLcpu: rat(%d), mode(%d), startend(%d)
[MDFS][WARNING] %s: Wrong %s(%d)
[MDFS][WARNING] %s: Wrong %s(%d)
[MDFS][WARNING] %s: Wrong %s(%d)
[MDFS][%d]SetDfsClock: Modem DFS Disabled!!
[MDFS][%d]SetDfsClock: Modem MCW[%d] Or MPLL[%d] are Off
[MDFS][%d]SetDfsClock: Rat(%d), mode(%d), r_maxmin(%d), IsIrat(%d), BreakCnt(%d), representative_clk(%d)
[MDFS][WARNING] %s: Wrong %s(%d)
[MDFS][%d]CheckMode: LteSpecialMode(%d), NrSpecialMode(%d), DfsMode(%d), [NumLteCc(%d), RxPath(%d)], NumNrCc(%d)
[MDFS][%d]ResetAllPrams
[MDFS][%d]ResetPrevPrams
[MDFS][%d]ResetCcRxInfo: rat(%d), NumLteCc(%d), NumNrCc(%d)
[MDFS][%d]CheckRatAfterEvent: Rat(%d), RateMode(%d), update(%d)
[HALMTX][%d]Wait: BreakCnt(%d)
[MDFS][WARNING]NullFunc()!!
