[IRAT U2L] uphy_CEutraMeasureStepFsm_step: EARFCN (%d), numOfEutraCells (%d), AGC1 (%d), AGC2 (%d), AFC (%d)
[IRAT U2L] uphy_CEutraMeasureStepFsm_step: EARFCN (%d), numOfEutraCells (%d), AGC1 (%d), AGC2 (%d), AFC (%d)
[IRAT U2L] uphy_CEutraMeasureStepFsm_step: cellId=%d, start (sfn, tti, offset)=(%d, %d, %d), duration (sfn, tti, offset)=(%d, %d, %d)
[IRAT U2L] uphy_CEutraMeasureStepFsm_step: cellId=%d, start (sfn, tti, offset)=(%d, %d, %d), duration (sfn, tti, offset)=(%d, %d, %d)
S0 ### Critical Error UmtsMessagePtr mMsg = NULL (%d)
S0 ### Critical Error UmtsMessagePtr mMsg = NULL (%d)
[IRAT U2L] uphy_CEutraMeasureStepFsm_processReplyInfo: numOfEutraCells (%d), EARFCN (%d), cellId (%d), cyType (%d), framePosition (%d), RSRP (%d), RSRQ (%d)
[IRAT U2L] uphy_CEutraMeasureStepFsm_processReplyInfo: numOfEutraCells (%d), EARFCN (%d), cellId (%d), cyType (%d), framePosition (%d), RSRP (%d), RSRQ (%d)
S0 ### Critical Error eutraCellMeasResultsList = NULL (%d)
S0 ### Critical Error eutraCellMeasResultsList = NULL (%d)
[IRAT U2L] uphy_CEutraMeasureStepFsm_processReplyInfo: AGC1 (%d), AGC2 (%d), AFC (%d)
[IRAT U2L] uphy_CEutraMeasureStepFsm_processReplyInfo: AGC1 (%d), AGC2 (%d), AFC (%d)
