No Memory allocated for rrc_MeasurementsInterLayerMsg_SetCompressedModeStatusInfo ILM
No Memory allocated for rrc_MeasurementsInterLayerMsg_SetMid
Index >= ArraySize
No Memory allocated for rrc_MeasurementsInterLayerMsg_SetCompressedModeTgpsStatusInfo
