Uhal Stops PCCPCH Phych %d (type=%d, RlsStr=%x)
Uhal Stops SCCPCH Phych %d (type=%d, RlsStr=%x)
Uhal Stops DL DPCH Phych %d (type=%d, RlsStr=%x)
Uhal Stops PICH Phych %d (type=%d, RlsStr=%x)
Uhal Stops AICH Phych %d (type=%d, RlsStr=%x)
Uhal Stops MICH Phych %d (type=%d, RlsStr=%x)
Uhal Stops SCCPCH_MBMS_RL0 Phych %d (type=%d, RlsStr=%x)
Uhal Stops SCCPCH_MBMS_RL1 Phych %d (type=%d, RlsStr=%x)
Uhal Stops SCCPCH_MBMS_RL2 Phych %d (type=%d, RlsStr=%x)
Uhal Stops SCCPCH(0) for CBS Phych %d (type=%d, RlsStr=%x)
Uhal Stops SCCPCH(1) for CBS Phych %d (type=%d, RlsStr=%x)
Uhal Stops SCCPCH(2) for CBS Phych %d (type=%d, RlsStr=%x)
Uhal Stops ??? Phych %d (type=%d, RlsStr=%x)
activeStackId %d PhychType = %d
