(F) bit_conc: invalid length(%d)
CSI_PCR11_SM2_SubSampledPMI12: invalid tx_ant(%d)
CSI_PCR11_SM1_SubSampledPMI1RI: invalid tx_ant(%d)
CSI_PCR21_SubSampledPMI2: invalid tx_ant(%d)
ACQI: LTE-U Zero CQI report. cc_idx(%d), proc_idx(%d), set_idx(%d), atti(%d), off_state(%d), zero_cqi_ind(%d)
ACQI: LAA High CQI override. cc_idx(%d), proc_idx(%d), set_idx(%d), atti(%d), off_state(%d), zero_cqi_ind(%d)
ACQI: LAA Periodic CQI override. cc_idx(%d), proc_idx(%d), set_idx(%d), atti(%d), off_state(%d), zero_cqi_ind(%d)
(F) DL_Rank4_flag set due to rank3,4 report @ 2RX. aperiodic, cc_idx(%d), proc_idx(%d), set_idx(%d)
PCQI: override cdrx_init_csi
PCQI: Zero CQI report. cc_idx(%d), proc_idx(%d), set_idx(%d), atti(%d), pcqi_type(%d), zero_cqi_ind(%d)
(F) DL_Rank4_flag set due to rank3,4 report @ 2RX. periodic, cc_idx(%d), proc_idx(%d), set_idx(%d)
PcsiDb: EnableRestore.
PcsiDb: Restore. cc_idx(%d), restore_flag(%d), valid(0x%x), earfcn(%d), cell_id(%d), tm(%d), ri00(%d)
PcsiDb: PrepareBackup. cc_idx(%d), active(%d), atti(%d), earfcn(%d), cell_id(%d), tm(%d)
PcsiDb: Backup. valid(%d,%d,%d,%d,%d,%d)
wakeup_time adjust : curr/orig/adjusted_atti(%d,%d,%d), pcqi_srch(%d), advance(%d), sleep_time(%d), max_cqi_hist(0x%x)
