QuickSleep activation request (enableStatus:%d)
QuickSleep deactivated (bitmap:0x%x), previous1(%d), previous2(%d)
[QS_CONDITION][BEFORE] : qs_channelStatus(%d), snr(%d), doppler(%d) -> qs_off(0x%x)
[QS_CONDITION][AFTER] : qs_channelStatus(%d), snr(%d), doppler(%d) -> qs_off(0x%x)
QS_CONDITION_DYNAMIC, disableConditionCount(%d), cond_tdp_state/cond_channel/cond_dci/cond_crc/snr/dop(%06x), gap/csirs/mbsfn/crok/sf05(0x%05x), pseudoDci/dynamic/rstd/meas/sync(%05x), mibDec/sibUnknown/agap (%03x)
QSleep status changed: TTI/Status(%d/%d), (%d/%d)
[AS] RSRP timer(%d,%d) RSRP Offset(%d %d)
[AS] U/L RSRP (%d,%d), diff(%d), status(%d), RxRsrpOffset(%d,%d), TAS_enb(%d)
[AS] L/R RSRP (%d,%d), diff(%d), status(%d), RxRsrpOffset(%d,%d), meas_idx(%d)
[4RxD] CC0 RSRP (%d,%d,%d,%d), diff(%d,%d), meas_idx(%d)
HST_STATE(%d), TEST_SIM(%d), div_enb(0x%x), 2RX mode
ONE_RX CHECK_signalQuality, CurMode(%d), SelectedMode(%d), disableConditions(%d), caOn/crcBad/lowSnr(%03x), filteredSinr(%d), ant_sw_txpwr_en(%d), maxpwr_tworx(%d)
IPC:RX MODE_CHANGE_NOTIFY (to ARM) - antennaMode(%d), onerx_preMode(%d), caOn/crcBad/lowSnr(%03x), filteredSinr(%d)
[4RxD] Periodic 4Rx monitoring is skipped by DataInactiveStatus(%d) or MIMO Max(%d) or csi_static(%d)
[4RxD] Periodic 4Rx monitoring, AS_RX2_flag(%d), FourRx_RSRP_flag(%d), rxmode_bitmap(%d), FourRx_monitoring_trigger(%d)
[4RxD] div_enb(%d), div_num(%d), pActiveCC->num(%d)
[4RxD] idx(%d), frx_cck(%d), agg4rx_mode2(%d)
[4RxD] sinr_path (%d,%d,%d,%d), sinr_2rx(%d,%d,%d)
[4RxD] CC%d scheduling rate (%d), rb_size_ratio(%d), isVoLTEcall(%d), ueCategory(%d), mimo_max(%d), rxmode_bitmap(%d)
[4RxD] 4X4MIMO is configured and waiting for changing to 4Rx, check(%d), check timer(%d)
[4RxD] 4X4MIMO is configured and waiting for changing to 4Rx, check(%d), check timer(%d)
[4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
[4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
[4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
[4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
[4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
[4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
[4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
[4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
[4RxD] 4RxD is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
[4RxD] 4RxD is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
ABFRX: cgk1/cck1/detcnt2(%d), timer(%d), rsrp(%d,%d,%d,%d), rsrq(%d,%d,%d,%d)
[RXMODE] ipc(0x%x), mode_rpt,req,int,ext,curmode(0x%x,0x%x,0x%x,0x%x,0x%x), tm(0x%x), tas_enb2/div_enb2/volte1/equip1/testsim1/datainact1(0x%08x)
IPC:RX MODE_CHANGE_NOTIFY (to ARM): %d, CC%d cur_rx_mode: %d
IPC:RX MODE_CHANGE_NOTIFY is skipped (to ARM), CC%d cur_rx_mode: %d
Best2RxSel: cck(%d), cand_bitmap(0x%x)
Best2RxSel: cck(%d), cand1,2,3(%d,%d,%d), rxc01,02,03(%d,%d,%d)
[4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
[4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
[4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
[4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
[4RxD] PRX1+DRX1 is selected due to TX swap(L->U) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
[4RxD] PRX1+DRX1 is selected due to TX swap(U->L) condition, CC0_tx_swap_enb(%d), ant_sw_maxtxpwr_en(%d), ant_sw_txpwr_en(%d), rsrp_diff_rx01(%d), TAS_status(%d)
