LAA_Release laa_sf_info(0x%x)
[LAA] nslot=1, cc_idx(%d) LAA_DETECTION_MODE_CCx(0x%x), CCx_LAA_FAD_CON0(0x%x), CCx_LAA_FAD_SERTHR(0x%x)
[LAA] nslot=0, cc_idx(%d) LAA_DETECTION_MODE_CCx(0x%x)
[LAA] nslot = 1, CCx_LAA_INIT_TTI(0x%x)
[LAA] nslot = 1, LAA_CTRL_CH_DEMAPPING(0x%x)
[LAA] nslot = 1, RADDR_LAA_CRS_CE_INFO(0x%x)
[LAA] start_partial_on(%d),end_partial_on(%d),laa_pbch_off(%d),laa_sync_off(%d),end_symbol_num(%d),tdd_sync_tti_on(%d)
[LAA] RADDR_LAA_SF_INFO(0x%x)
[LAA] nslot = 1, MCG_LAST_RS_CHK(0x%x), SCG_LAST_RS_CHK(0x%x)
[LAA] Status: slot(0), active(CC1-CC7):(%07d), cell_group:(%07d), sleep_state:(%07d), dci_detected:(%05d), detectionmode:(%07d), detected_slot:(%07d), sfcfg_LAA:(%07x)
[LAA] Status: slot(1), active(CC1-CC7):(%07d), is_dmtc:(%07d), sleep_state:(%07d), dci_detected:(%05d), detectionmode:(%07d), detected_slot:(%07d), sfcfg_LAA:(%07x)
[LAA] LAA Interrupt atti(%d), slot(%d), CG(%d), MCG_DL_DETECT_MON(0x%x), SCG_DL_DETECT_MON(0x%x)
