Rnti_SetAgapRnti_CSS_ON org(0x%x)
Rnti_SetAgapRnti_USS_ON org(0x%x)
(F) Support FORMAT1, 1A for Temp C-RNTI TM(%d)
(F) Remove T-CRNTI cause by C-RNTI(0x%x)
(F) Set T-CRNTI only CSS, C-RNTI(0x%x)
Rnti_RegisterRnti CSS(0x%x)(0x%x)(0x%x)(0x%x)(0x%x)(0x%x)(0x%x)
Rnti_RegisterRnti USS(0x%x)(0x%x)
CC(%d) Rnti_RegisterRnti_on: CSS(0x%x) USS(0x%x)/ dl_ind (0x%x)
Rnti_Init: mode(%d) cell_group(%d)
