Event 1A (MID%i)
Event 1B (MID%i)
Event 1C (MID%i)
Event 1D (MID%i)
Event 1E (MID%i)
Event 1F (MID%i)
Event 1J (MID%i)
Unknown Event (MID%i)
[rrc_IEIntraFreqEventResults_AddPrimaryCPICHInfo] This PSC(%d) is already existed in the EventResults(%d)
