IsPrachTfcsPresent: Unsupported protocol version
rrc_ieTrChUlCmnInfo_processIeImpl: [FAILURE] PRACH TFCS present
Unsupported Proto Ver %d
rrc_ieTrChUlCmnInfo_processChildIes:Asn_modeSpecificInfo_tdd_8_chosen
rrc_ieTrChUlCmnInfo_processChildIes:tfcs_ID = %d
rrc_ieTTrChUlCmnInfo_processChildIes:Asn_fullTFCS_chosen
