EQ, eq0_18 %d, eq0_19 %d, eq0_20 %d, eq1_18 %d, eq1_19 %d, eq1_20 %d, PeakTapEq3|Eq2|Eq1|Eq0 0x%08X
EQ, eq2_18 %d, eq2_19 %d, eq2_20 %d, eq3_18 %d, eq3_19 %d, eq3_20 %d, eq0PeakVal %d
hspa_Dsp_Ref_Slot_isr (%d)
hspa_Hclp_Sw_isr (%d)
log_hclpRtIsrTic %d, log_hclpSwIsrTic %d, o_FRT_CE_COM_CTRL1 %d, tt_trace0 %d
hspa_Hclp_Rt_isr (%d)
hspa_Hclp_Nrt_isr (%d)
hspa_Hclp_Nrt_Reg_isr (%d)
hspa_Scch_P1_Done_isr (%d)
hspa_Scch_P1_Done_Assist_isr (%d)
hspa_Scch_P2_Done_isr (%d)
hspa_Scch_P2_Done_Assist_isr (%d)
hspa_Dsch_Dec_Done_isr (%d)
hspa_Dsch_Dec_Done_Assist_isr (%d)
hspa_Tx_Hs_isr (%d)
hspa_Tx_Slot_0_isr (%d)
hspa_Tx_Slot_1_isr (%d)
hspa_Tx_Slot_2_isr (%d)
hspa_Tx_Slot_3_isr (%d)
hspa_Tx_Slot_4_isr (%d)
hspa_Data_Mover_Agc_isr (%d)
hspa_Data_Mover_Ce_isr (%d)
hspa_Data_Mover_Ce_isr gated by sw, swGatingState_ce(%d)
hspa_Data_Mover_Mtg_isr (%d)
hspa_Data_Mover_Eq_isr (%d)
hspa_Data_Mover_Eta_isr (%d)
hspa_Data_Mover_Cpich_Sym_isr (%d)
hspa_Data_Mover_Cpich_Sym_isr gated by sw, swGatingState_sinr(%d)
