rrc_HandoverFromUtranFail_setInterRatHandoverFailure: inappropriate HandoverFailCause
rrc_HandoverFromUtranFail_setInterRatHandoverFailure: invalid HandoverFailCause
rrc_HandoverFromUtranFail_setInterRatHandoverFailureWithProto: inappropriate HandoverFailCause
rrc_HandoverFromUtranFail_setInterRatHandoverFailureWithProto: invalid HandoverFailCause
rrc_HandoverFromUtranFail_setEutraMessage: Failed to Free ptr
