rrc_CellChangeOrderFail_setInterRatChangeFailure: inappropriate ChangeFailCause
rrc_CellChangeOrderFail_setInterRatChangeFailure: invalid ChangeFailCause
rrc_CellChangeOrderFail_setInterRatChangeFailure: inappropriate ChangeFailCause
rrc_CellChangeOrderFail_setInterRatChangeFailure: invalid ChangeFailCause
