rrc_RbReleaseCmp_setStartValue
rrc_RbReleaseCmp_setStartValue - cs entry present
rrc_RbReleaseCmp_setStartValue - ps entry present
rrc_RbReleaseCmp_setTransId
rrc_RbReleaseCmp_setIntProtActInfo
rrc_RbReleaseCmp_setRbCiphActTimeInfo
rrc_RbReleaseCmp_setCountCActTime
rrc_RbReleaseCmp_setCounterSyncInfo
rrc_RbReleaseCmp_suppressStartValueSend
