L1CfgMonitorRSSI sniff startOffset [%d] startdsp [%d] stopdsp [%d]
L1CfgMonitorRSSI no sniff startOffset [%d] startdsp [%d] stopdsp [%d]
L1CfgMonitorRSSI_RFCAL startOffset [%d] startdsp [%d] stopdsp [%d]
L1CfgMonitorRSSI_RFCAL startOffset [%d] startdsp [%d] stopdsp [%d]
L1CfgMonitorRSSI_Irat startOffset [%d] startdsp [%d] stopdsp [%d]
L1CfgStartFbAcquire sniff startOffset [%d] startdsp [%d]
L1CfgStartFbAcquire no sniff startOffset [%d] startdsp [%d]
###L1CfgStartIRATFbAcquire endoffset Org[%d] Modified[%d]
L1CfgStartFbAcquire no sniff startOffset [%d] startdsp [%d]
L1CfgSbAcquire no sniff startOffset [%d] startdsp [%d] stopdsp [%d]
L1CfgPtmSbAcquire startOffset [%d] startdsp [%d] stopdsp [%d]
L1CfgSbAcquire sniff startOffset [%d] startdsp [%d] stopdsp [%d]
L1CfgSbAcquire no sniff startOffset [%d] startdsp [%d] stopdsp [%d]
