Warning: RachDataMsg dataPayload->TrChInfoReq.Tfi out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachDataMsg dataPayload->Asc out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachDataMsg dataPayload->TrChInfoReq.NoTbs out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning : RachDataMsg dataPayload->TrChInfoReq.Data is NULL
Warning : RachDataMsg dataPayload->TrChInfoReq.Data is NULL
Warning: RachModifyMsg rachResourcesModifyReqMsg->payload.UlInterference out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Message received after Non UMTS rat mode req, so ignored transceiver = %d stackId = %d
Message received after Non UMTS rat mode req, so ignored transceiver = %d stackId = %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->primaryCpichTxPower out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->constantValue out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->ulInterference out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachPowerOffset.powerRampStep out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachPowerOffset.maxPreambleRetransission out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.minPrachSpreadingFactor out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.preambleScrCodeNr out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->prachInfo.puncturingLimit out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->numOfAsc out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg accessServiceClassArray[n].availableSignatureStartIndex out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg accessServiceClassArray[n].availableSignatureEndIndex out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->numOfUlCtfc out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->ulPowerOffsetInfoArray[n].betaC out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->ulPowerOffsetInfoArray[n].betaD out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->ulPowerOffsetInfoArray[n].powerOffsetPpm out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->rachInfo.trChId out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->rachInfo.trChType out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->rachInfo.semiStaticInfo.tti out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->rachInfo.semiStaticInfo.channelCoding out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->rachInfo.semiStaticInfo.rateMatchingArgument out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->rachInfo.semiStaticInfo.crcSize out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->rachInfo.semiStaticInfo.codingRate out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->primaryScrCode out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->aichInfo.chanCode out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
Warning: RachResourcesConfigMsg rachResourcesConfigReqPayload->aichInfo.aichPowerOffset out of bounds. Value %d, Bounds %d and %d. File ../../../HEDGE/3GFT/UL1/UL1C/ChMgt/Rach/Code/Src/uphy_CRachResources.c Line %d
