RrmSubBlkMeasReportMsgApi::RrmSubBlkMeasReportMsgApi()
RrmSubBlkMeasReportMsgApi::~RrmSubBlkMeasReportMsgApi()
RrmSubBlkMeasReportMsgApi::Init()
RrmSubBlkMeasReportMsgApi::SetServCellMeasResults::RsType(SSB), Quantity(Rsrp), Rsrp(%d), RSRPReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetServCellMeasResults::RsType(SSB), Quantity(Rsrq), Rsrq(%d), RSRQReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetServCellMeasResults::RsType(SSB), Quantity(Sinr), Sinr(%d), RSRQReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetServCellMeasResults::RsType(SSB), Quantity(empty)
Quantity(Rsrp)
Rsrp(%d), RSRPReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetServCellMeasResults::RsType(CSIRS), Quantity(Rsrp), Rsrp(%d), RSRPReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetServCellMeasResults::RsType(CSIRS), Quantity(Rsrq), Rsrq(%d), RSRQReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetServCellMeasResults::RsType(CSIRS), Quantity(Sinr), Sinr(%d), RSRQReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetServCellMeasResults::RsType(CSIRS), Quantity(empty)
Quantity(Rsrp)
Rsrp(%d), RSRPReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetServCellMeasResults::RsType(empty)
RrmSubBlkMeasReportMsgApi::SetCellMeasResults::RsType(SSB), Quantity(Rsrp), Rsrp(%d), RSRPReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetCellMeasResults::RsType(SSB), Quantity(Rsrq), Rsrq(%d), RSRQReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetCellMeasResults::RsType(SSB), Quantity(Sinr), Sinr(%d), RSRQReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetCellMeasResults::RsType(SSB), Quantity(empty)
Quantity(Rsrp)
Rsrp(%d), RSRPReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetCellMeasResults::RsType(CSIRS), Quantity(Rsrp), Rsrp(%d), RSRPReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetCellMeasResults::RsType(CSIRS), Quantity(Rsrq), Rsrq(%d), RSRQReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetCellMeasResults::RsType(CSIRS), Quantity(Sinr), Sinr(%d), RSRQReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetCellMeasResults::RsType(CSIRS), Quantity(empty)
Quantity(Rsrp)
Rsrp(%d), RSRPReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetCellMeasResults::RsType(empty)
RrmSubBlkMeasReportMsgApi::SetCellMeasResultsEutra::RsType(SSB), Quantity(Rsrp), Rsrp(%d), RSRPReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetCellMeasResultsEutra::RsType(SSB), Quantity(Rsrq), Rsrq(%d), RSRQReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetCellMeasResultsEutra::RsType(SSB), Quantity(Sinr), Sinr(%d), RSRQReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetCellMeasResultsEutra::Quantity(empty) Set default Quantity(Rsrp)
Rsrp(%d), RSRPReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetCellMeasResultsUtra::Quantity(Rscp), Rscp(%d), RSCPeportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetCellMeasResultsUtra::Quantity(EcNo), EcNo(%d), EcNoReportMapping(%d)
RrmSubBlkMeasReportMsgApi::SetCellMeasResultsUtra::Quantity(empty) Set default Quantity(Rscp)
Rscp(%d), RSCPReportMapping(%d)
RrmSubBlkMeasReportMsgApi::GetmeasResultBestNeighCell::ServingCell is not
RrmSubBlkMeasReportMsgApi::GetmeasResultBestNeighCell::ServingCell do not have MeasID
RrmSubBlkMeasReportMsgApi::GetmeasResultBestNeighCell::empty IntraFreqInfo
RrmSubBlkMeasReportMsgApi::MakeNrReportMsgForSCell::ServCellGroupInfoNrPtr is NULL::_eval_
RrmSubBlkMeasReportMsgApi::GetSCellmeasResultBestNeighCell::ServingCell do not have MeasID
RrmSubBlkMeasReportMsgApi::GetSCellmeasResultBestNeighCell::empty IntraFreqInfo
RrmSubBlkMeasReportMsgApi::GetSCellmeasResultBestNeighCell::SCellInfo is NULL
RrmSubBlkMeasReportMsgApi::GetMaxCell::cell is not valid
RrmSubBlkMeasReportMsgApi::GetMaxCell::Sorting Error. ReportConfigNR_Rsrp(%d), ReportConfigNR_Rsrq(%d), ReportConfigNR_Sinr(%d), (CellID(%d) isValid_I(%d)), (CellID(%d) isValid_J(%d))
