RrmSubBlkMeasReportCommonConfig::RrmSubBlkMeasReportCommonConfig()
RrmSubBlkMeasReportCommonConfig::~RrmSubBlkMeasReportCommonConfig()
RrmSubBlkMeasReportCommonConfig::Init()
RrmSubBlkMeasReportCommonConfig::UpdateReportConfigInfo::MeasID(%d) accumulation(%d) ReportConfigChoice(%d)
>> (reportType_reportCGI) reportType(%d), CellForWhichToReportCGI(%d)
>> MeasInfo's reportType is not valid
RrmSubBlkMeasReportCommon::UpdateReportConfigInfo::Unavailable InterRatType( %d)
RrmSubBlkMeasReportCommonConfig::UpdateReportConfigInfo::Unavailable MeasInfo type(%d)
>> (reportType_periodical) reportType(%d), RsType(%d), IncludeBeamMeas(%d), MaxReportCells(%d)
>> (reportType_periodical)(ReportQuantityCell) Rsrp(%d), Rsrq(%d), Sinr(%d)
>> (reportType_periodical)(ReportQuantityRsIdx) ReportQuantityRsIdxPresent(%d), Rsrp(%d), Rsrq(%d), Sinr(%d)
>> (reportType_periodical) MaxNrofRsIndexesToReportPresent(%d), MaxNrofRsIndexesToReport(%d)
>> (reportType_eventTriggered) empty EventIdChoice(%d)
>> (reportType_eventTriggered)(NRRRCDB_EventId_A%d) TriggerQuantity(%d), ReportOnLeave(%d), ReportAddNeighMeasPresent(%d)
>> (reportType_eventTriggered) reportType(%d), RsType(%d), IncludeBeamMeas(%d), MaxReportCells(%d)
>> (reportType_eventTriggered)(ReportQuantityCell) Rsrp(%d), Rsrq(%d), Sinr(%d)
>> (reportType_eventTriggered)(ReportQuantityRsIdx) ReportQuantityRsIdxPresent(%d), Rsrp(%d), Rsrq(%d), Sinr(%d)
>> (reportType_eventTriggered) MaxNrofRsIndexesToReportPresent(%d), MaxNrofRsIndexesToReport(%d)
RrmSubBlkMeasReportCommonConfig::UpdateReportConfigInfo::(NRRRCDB_CondEventId_A3) TriggerQuantity(%d) ReportOnLeave(%d)
RrmSubBlkMeasReportCommonConfig::UpdateReportConfigInfo::(NRRRCDB_EventId_A5) TriggerQuantity(%d) ReportOnLeave(%d)
RrmSubBlkMeasReportCommonConfig::UpdateReportConfigInfo::empty EventIdChoice (%d)
>> (reportType_condTriggerConfig) reportType(%d), RsType(%d), IncludeBeamMeas(%d), MaxReportCells(%d)
>> (reportType_condTriggerConfig) ReportAddNeighMeasPresent(%d), ReportAddNeighMeas(%d)
>> (reportType_condTriggerConfig) (ReportQuantityCell) accumulation(%d) Rsrp(%d), Rsrq(%d), Sinr(%d)
>> (reportType_condTriggerConfig) (ReportQuantityRsIdx) accumulation(%d) Rsrp(%d), Rsrq(%d), Sinr(%d)
[N2L] RrmSubBlkMeasReportCommonConfig::UpdateReportConfigInfo::(reportType_periodical) reportType(%d), RsType(%d), IncludeBeamMeas(%d), MaxReportCells(%d)
[N2L] RrmSubBlkMeasReportCommonConfig::UpdateReportConfigInfo::(reportType_periodical) (ReportQuantityCell) Rsrp(%d), Rsrq(%d), Sinr(%d)
[N2L] RrmSubBlkMeasReportCommonConfig::UpdateReportConfigInfo::(NRRRCDB_EventId_B1) TriggerQuantity(%d) ReportOnLeave(%d)
[N2L] UpdateReportConfigInfo::(NRRRCDB_EventId_B2) TriggerQuantity(%d) ReportOnLeave(%d)
[N2L] UpdateReportConfigInfo::empty EventIdChoice (%d)
[N2L] UpdateReportConfigInfo::(reportType_eventTriggered) reportType(%d), RsType(%d), IncludeBeamMeas(%d), MaxReportCells(%d)
[N2L] UpdateReportConfigInfo::(reportType_eventTriggered) ReportAddNeighMeasPresent(%d), ReportAddNeighMeas(%d)
[N2L] UpdateReportConfigInfo::(reportType_eventTriggered) (ReportQuantityCell) Rsrp(%d), Rsrq(%d), Sinr(%d)
RrmSubBlkMeasReportCommonConfig::UpdateReportConfigInfo::MeasInfo's reportType is not valid
[N2U] UpdateReportConfigInfoInterRATUtra::(reportType_periodical) reportType(%d), MaxReportCells(%d), Rscp(%d), EcNo(%d)
[N2U] UpdateReportConfigInfoInterRATUtra::(NRRRCDB_EventId_B1_UtraFdd) ReportOnLeave(%d)
[N2U] UpdateReportConfigInfoInterRATUtra::(NRRRCDB_EventId_B2_UtraFdd) ReportOnLeave(%d)
[N2U] UpdateReportConfigInfoInterRATUtra::empty EventIdChoice (%d)
[N2U] UpdateReportConfigInfoInterRATUtra::(reportType_eventTriggered) reportType(%d), MaxReportCells(%d)
[N2U] UpdateReportConfigInfoInterRATUtra::(reportType_eventTriggered) ReportAddNeighMeasPresent(%d), ReportAddNeighMeas(%d)
[N2U] UpdateReportConfigInfoInterRATUtra::(reportType_eventTriggered) (ReportQuantityCell) Rscp(%d), EcNo(%d)
UpdateReportConfigInfo::MeasInfo's reportType is not valid
Unexpected value for rMeasInfo.ReportConfig.ReportConfigNR.Choice(%d)
Unexpected value for rMeasInfo.ReportConfig.ReportConfigInterRAT.Choice(%d)
RrmSubBlkMeasReportCommonConfig::GetEventTriggeredReportAmount::ReportAmount value(%d), EventTriggeredReportAmount[ReportAmount](%d), numberOfReportsSent(%d)[N2L]
RrmSubBlkMeasReportCommonConfig::GetEventTriggeredReportAmount::result_s32(%d)[N2L]
RrmSubBlkMeasReportCommonConfig::GetEventTriggeredReportAmount::error ReportAmount value(%d), MeasID(%d)[N2L]
