RrmNrMeasSvError::RRM_L1C_MEAS_STOP_CNF_ErrorHandler => Send Cnf with fail
RrmNrMeasSvError::RRM_RRM_MEAS_STATE_REQ_ErrorHandler => Send Cnf with fail
RrmNrMeasSvError::RRM_TIMER_MEAS_EVAL_IND_ErrorHandler
RrmNrMeasSvError::RRM_TIMER_MR_INTERVAL_IND_ErrorHandler
RrmNrMeasSvError::RRM_RRM_MAKE_MEAS_REPORT_IND_ErrorHandler
RrmNrMeasSvError::RRM_RRM_MAKE_MEAS_RESULT_IND_ErrorHandler
RrmNrMeasSvError::RRM_LTERRM_LTE_MEAS_RESULT_IND_ErrorHandler
RrmNrMeasSvError::RRM_LTERRM_LTE_OBJECT_CHECK_CNF_ErrorHandler
RrmNrMeasSvError::RRM_RRC_DELAY_REPORT_IND_ErrorHandler
