L1_UL_IDLE
L1_DL_IDLE
C_Cnf DL %d
Pending DL REL_REQ sent
Pending DL Cnf rcd
Sent delayed UL release request
L1_DL_TRANSFER
L1_DL_RELEASE
L1_DL_DELAYED_RELEASE
L1_UL_TRANSFER_REL
C_Cnf UL %d
Pending UL REL_REQ sent
Pending UL Cnf rcd
Sent delayed DL REL REQ
L1_DL_RELEASE
L1_UL_IDLE
L1_UL_SINGLE_BLK
L1_UL_SINGLE_BLK_REL
L1_UL_PRE_ONE_PHASE
L1_UL_PRE_ONE_PHASE_REL
L1_UL_PRE_TWO_PHASE
L1_UL_PRE_TWO_PHASE_REL
L1_UL_TWO_PHASE
L1_UL_S2_TWO_PHASE
L1_UL_S2_TWO_PHASE_REL
L1_UL_TRANSFER
L1_UL_TRANSFER_REL
L1_UL_DELAYED_RELEASE
UL PH_CON_REQ is rejected [%d]
L1_UL_IDLE
DL Reject!
L1_DL_IDLE
C_Req DL %d
C_Req UL %d
C_Req Both (U)%d (D)%d
DL Released
L1_DL_IDLE
UL Released
L1_UL_IDLE
RelR DL Ignored dtm_state%d l1al_dl_state(%d)
RelR DL %d (%d)
Stop %s
DL to be released before establish Or Delayed Release cleared : RF Unavailable case
L1_DL_PRE_TRANSFER_REL
Entering L1_DL_DELAYED_RELEASE state, UL state:%d
Pending DL REL REQ exists
L1_DL_IDLE
L1_DL_TRANSIENT
L1_DL_PRE_TRANSFER_REL
L1_DL_TRANSFER
L1_DL_RELEASE
L1_DL_DELAYED_RELEASE
Rel Err %d DL
RelR UL Ignored dtm_state%d l1al_ul_state(%d)
RelR UL %d (%d)
Stop %s
Stop Rach Delay timer if running
Stop %s
Stop PDCH REQ Delay timer if running
UL to be released before establish Or Delayed Release cleared : RF Unavailable case Or
Rel Err %d UL
L1_UL_IDLE
L1_UL_SINGLE_BLK
L1_UL_SINGLE_BLK_REL
L1_UL_PRE_ONE_PHASE
L1_UL_PRE_ONE_PHASE_REL
L1_UL_PRE_TWO_PHASE
L1_UL_PRE_TWO_PHASE_REL
L1_UL_TWO_PHASE
L1_UL_S2_TWO_PHASE
L1_UL_S2_TWO_PHASE_REL
L1_UL_TRANSFER
L1_UL_TRANSFER_REL
L1_UL_DELAYED_RELEASE
Entering L1_UL_DELAYED_RELEASE state
Pending UL REL REQ exists
L1_UL_S2_TWO_PHASE
L1_UL_S2_TWO_PHASE_REL
L1_UL_TRANSFER
L1_UL_TRANSFER_REL
L1_UL_DELAYED_RELEASE
Null Pointer Return
L1_DL_TRANSIENT
Pending DL Cnf exists
CR Failure 1
Pending UL Cnf exists
CR Failure 2:%d
L1_UL_IDLE
L1_UL_SINGLE_BLK
L1_UL_SINGLE_BLK_REL
L1_UL_PRE_ONE_PHASE
L1_UL_PRE_ONE_PHASE_REL
L1_UL_PRE_TWO_PHASE
L1_UL_PRE_TWO_PHASE_REL
L1_UL_TWO_PHASE
L1_UL_S2_TWO_PHASE
L1_UL_S2_TWO_PHASE_REL
L1_UL_TRANSFER
L1_UL_TRANSFER_REL
L1_UL_DELAYED_RELEASE
L1_DL_TRANSIENT
L1_UL_S2_TWO_PHASE
Pending BOTH Cnf exists
