[FBRX][ON] ADC_FIFO_PTR_CFG2(0x%x, 0x%x, 0x%x)
[FBRX] POW_MEAS_CFG0 %x, POW_MEAS_CFG1 %x
[FBRX] DCR_ACCUM_VALUE0 %x
[FBRX] FBRX_AGC0 %x, FBRX_DCR0 %x, temp_FIRCONTROLSELREQ %x
[FBRX][ON] FBRX_AGC0 0x%X, FBRX_DCR0 0x%X, FIRCONTROLSELREQ 0x%X, RFD_2G_FBRX_GSMRFD_SW_RESET 0x%x, 2G_PATH_SEL_MSB 0x%X, DCR_ACCUM_VALUE0 0x%X
[FBRX][ON] FBRX_AGC0 0x%X, FBRX_DCR0 0x%X, FIRCONTROLSELREQ 0x%X, RFD_2G_FBRX_GSMRFD_SW_RESET 0x%x, 2G_PATH_SEL_MSB 0x%X, DCR_ACCUM_VALUE0 0x%X
[FBRX][OFF] ADC_FIFO_PTR_CFG2(0x%x, 0x%x, 0x%x)
[FBRX][OFF] DCR_ACCUM_VALUE0 %x, POW_MEAS_VALUE0 %x
