[RFCTRL] RFIF_HI_SPEEDY_Debug_Log: BLK_EN[0x%X] TRIG_MASK0[0x%X]
[RFCTRL] RFIF_HI_SPEEDY_Debug_Log: REQ_STATUS[0/1][0x%X/0x%X] SELECT_STATUS[0/1][0x%X/0x%X] FLAG_MASK[0/1][0x%X/0x%X]
[RFCTRL] RFIF_HI_SPEEDY_Debug_Log: FORMATGEN => CTRL[0x%X] WR[0x%X] RD[0x%X] CLK_RATE[0x%X] SIG_CTRL[0x%X]
[RFCTRL] RFIF_HI_SPEEDY_Debug_Log: FORMATGEN => BOOT_MODE_EN[0x%X] TIMEOUT[0x%X] TIMEOUT_RD[0x%X] STATE_RD[0x%X] READ0_DONE[0x%X]
[RFCTRL] RFIF_HI_SPEEDY_SW_Write: EXCEPTION CASE FIFO NOT CLEARED (%d) !!!!!!!, WriteCnt_2G : %d, addr : 0x%X
[RFCTRL] RFIF_HI_SPEEDY_SW_Read [addr: 0x%X] : FIFO NOT CLEARED!!! step: %d cnt: %d
[RFCTRL] NO RESPONSE from RFIC(TIME OUT)!!!!!!! [addr: 0x%X]
