[SIPC_1_SND] Tx NS_SOUND_VOLUME_REQ (usVolumeLevel=%d)
[SIPC_0_SND] Tx NS_SOUND_VOLUME_REQ (usVolumeLevel=%d)
[SIPC_1_SND] Tx NS_SOUND_MIC_MUTE_REQ (ucMuteStatus=%d)
[SIPC_0_SND] Tx NS_SOUND_MIC_MUTE_REQ (ucMuteStatus=%d)
[SIPC_1_SND] Tx NS_SOUND_PATH_REQ (ucPath=%d, ucMode=%d)
[SIPC_0_SND] Tx NS_SOUND_PATH_REQ (ucPath=%d, ucMode=%d)
[SIPC_1_SND] Tx NS_SOUND_LOOPBACK_REQ (ucStatus=%d, ucPath=%d)
[SIPC_0_SND] Tx NS_SOUND_LOOPBACK_REQ (ucStatus=%d, ucPath=%d)
[SIPC_1_SND] Tx NS_SOUND_VIDEO_CALL_REQ (ucVtMode=%d)
[SIPC_0_SND] Tx NS_SOUND_VIDEO_CALL_REQ (ucVtMode=%d)
[SIPC_1_SND] Tx NS_SOUND_CLOCK_REQ (ucStatus=%d)
[SIPC_0_SND] Tx NS_SOUND_CLOCK_REQ (ucStatus=%d)
[SIPC_1_SND] Tx NS_SOUND_TWO_MIC_SOL_CON_REQ (ucMode=%d)
[SIPC_0_SND] Tx NS_SOUND_TWO_MIC_SOL_CON_REQ (ucMode=%d)
[SIPC_1_SND] Tx NS_SOUND_DHA_CON_REQ (ucMode=%d, ucSelect=%d)
[SIPC_0_SND] Tx NS_SOUND_DHA_CON_REQ (ucMode=%d, ucSelect=%d)
[SIPC_1_SND] Tx NS_SOUND_DMV_MODE_REQ (ucMode=%d, ucStatus=%d)
[SIPC_0_SND] Tx NS_SOUND_DMV_MODE_REQ (ucMode=%d, ucStatus=%d)
[SIPC_1_SND] Tx NS_SOUND_CLK_MODE_REQ (Mode=%d)
[SIPC_0_SND] Tx NS_SOUND_CLK_MODE_REQ (Mode=%d)
[SIPC_1_SND] Tx NS_SOUND_AUDIO_DSP_SET_REQ (ucCallMode=%d)
[SIPC_0_SND] Tx NS_SOUND_AUDIO_DSP_SET_REQ (ucCallMode=%d)
