[SIPC_1_IMS] Rx NS_IMSCC_CHNL_GET_RSP (Channel Count=%d)
[SIPC_0_IMS] Rx NS_IMSCC_CHNL_GET_RSP (Channel Count=%d)
[SIPC_1_IMS] Rx NS_IMSCC_CHNL_SET_RSP (channel id=%d, result=0x%X)
[SIPC_0_IMS] Rx NS_IMSCC_CHNL_SET_RSP (channel id=%d, result=0x%X)
[SIPC_1_IMS] Rx NS_IMSCC_CODEC_GET_RSP (channel id=%d, codec count=%d)
[SIPC_0_IMS] Rx NS_IMSCC_CODEC_GET_RSP (channel id=%d, codec count=%d)
[SIPC_1_IMS] Rx NS_IMSCC_CODEC_SET_RSP (channel id=%d, result=0x%X)
[SIPC_0_IMS] Rx NS_IMSCC_CODEC_SET_RSP (channel id=%d, result=0x%X)
[SIPC_1_IMS] Rx NS_IMSCC_RTP_MEDIA_START_RSP (channel id=%d, result=0x%X)
[SIPC_0_IMS] Rx NS_IMSCC_RTP_MEDIA_START_RSP (channel id=%d, result=0x%X)
[SIPC_1_IMS] Rx NS_IMSCC_RTP_MEDIA_CHANGE_RSP (channel id=%d, result=0x%X)
[SIPC_0_IMS] Rx NS_IMSCC_RTP_MEDIA_CHANGE_RSP (channel id=%d, result=0x%X)
[SIPC_1_IMS] Rx NS_IMSCC_RTP_MEDIA_STOP_RSP (channel id=%d, result=0x%X)
[SIPC_0_IMS] Rx NS_IMSCC_RTP_MEDIA_STOP_RSP (channel id=%d, result=0x%X)
[SIPC_1_IMS] Rx NS_IMSCC_DTMF_SET_RSP (channel id=%d, result=0x%X)
[SIPC_0_IMS] Rx NS_IMSCC_DTMF_SET_RSP (channel id=%d, result=0x%X)
[SIPC_1_IMS] Rx NS_IMSCC_DTMF_RSP (channel id=%d, result=0x%X)
[SIPC_0_IMS] Rx NS_IMSCC_DTMF_RSP (channel id=%d, result=0x%X)
[SIPC_1_IMS] Rx NS_IMSCC_STAT_GET_RSP (channel id=%d)
[SIPC_0_IMS] Rx NS_IMSCC_STAT_GET_RSP (channel id=%d)
[SIPC_1_IMS] Rx NS_IMSCC_OPTION_SET_RSP (channel id=%d, result=0x%X)
[SIPC_0_IMS] Rx NS_IMSCC_OPTION_SET_RSP (channel id=%d, result=0x%X)
[SIPC_1_IMS] Rx NS_IMSCC_RTP_TIMEOUT_IND (channel id=%d)
[SIPC_0_IMS] Rx NS_IMSCC_RTP_TIMEOUT_IND (channel id=%d)
[SIPC_1_IMS] Rx NS_IMSCC_RTCP_TIMEOUT_IND (channel id=%d)
[SIPC_0_IMS] Rx NS_IMSCC_RTCP_TIMEOUT_IND (channel id=%d)
[SIPC_1_IMS] Rx NS_IMSCC_IMS_ENGINE_RSP (result=0x%X)
[SIPC_0_IMS] Rx NS_IMSCC_IMS_ENGINE_RSP (result=0x%X)
[SIPC_1_IMS] Rx NS_IMSCC_FRAMETIME_GET_RSP (channel=%d, )
[SIPC_0_IMS] Rx NS_IMSCC_FRAMETIME_GET_RSP (channel=%d, )
[SIPC_1_IMS] Rx NS_IMSCC_FRAMETIME_NTF (operation=%d, channel=%d, RTPtime=%d, NTP_LS=%d, NTP_MS=%d)
[SIPC_0_IMS] Rx NS_IMSCC_FRAMETIME_NTF (operation=%d, channel=%d, RTPtime=%d, NTP_LS=%d, NTP_MS=%d)
[SIPC_1_IMS] Rx NS_IMSCC_OPTION_INFO_IND (Operation=%d, Channel id=%d, BitRate=%u, Event=%d, Volume=%d, Duration=%d, EndBit=%d)
[SIPC_0_IMS] Rx NS_IMSCC_OPTION_INFO_IND (Operation=%d, Channel id=%d, BitRate=%u, Event=%d, Volume=%d, Duration=%d, EndBit=%d)
[SIPC_1_IMS] Rx NS_IMSCC_TUNEAWAY_SET_RSP (Result=%d)
[SIPC_0_IMS] Rx NS_IMSCC_TUNEAWAY_SET_RSP (Result=%d)
