[SIPC_1_PB] Invalid cmd type (main=0x%X, sub=0x%X, type=0x%X)
[SIPC_0_PB] Invalid cmd type (main=0x%X, sub=0x%X, type=0x%X)
[SIPC_1_PB] Undefined cmd (main=0x%X, sub=0x%X, type=0x%X)
[SIPC_0_PB] Undefined cmd (main=0x%X, sub=0x%X, type=0x%X)
[SIPC_1_PB] sipcSecCheckSimStatus failure
[SIPC_0_PB] sipcSecCheckSimStatus failure
[SIPC_1_PB] sipcPbCheckSimPbStatus() : PB initialization is failed
[SIPC_0_PB] sipcPbCheckSimPbStatus() : PB initialization is failed
[SIPC_1_PB] sipcPbCheckSimPbStatus() : PB is still initializing
[SIPC_0_PB] sipcPbCheckSimPbStatus() : PB is still initializing
[SIPC_1_PB] ucSubParamLen=%d
[SIPC_0_PB] ucSubParamLen=%d
[SIPC_1_PB] Tx Phone Book Access RSP (mode=0x%X, PB storage type=0x%X, index=%d, next index=%d)
[SIPC_0_PB] Tx Phone Book Access RSP (mode=0x%X, PB storage type=0x%X, index=%d, next index=%d)
[SIPC_1_PB] Tx Phone Book Access NTF (mode=0x%X, PB storage type=0x%X, index=%d)
[SIPC_0_PB] Tx Phone Book Access NTF (mode=0x%X, PB storage type=0x%X, index=%d)
[SIPC_1_PB] Tx Phone Book Storage RSP (PB storage type=0x%X, total count=%d, used count=%d)
[SIPC_0_PB] Tx Phone Book Storage RSP (PB storage type=0x%X, total count=%d, used count=%d)
[SIPC_1_PB] Tx Phone Book Storage List RSP (selected slot=0x%X, PB List=0x%04X)
[SIPC_0_PB] Tx Phone Book Storage List RSP (selected slot=0x%X, PB List=0x%04X)
[SIPC_1_PB] Tx Phone Book Entires Information RSP (PB storage type=0x%X, index min=%d, index max=%d, num max=%d, text max=%d)
[SIPC_0_PB] Tx Phone Book Entires Information RSP (PB storage type=0x%X, index min=%d, index max=%d, num max=%d, text max=%d)
[SIPC_1_PB] Tx 3G Phone Book Capability RSP (selected slot=0x%X, num of PB fields=%d)
[SIPC_0_PB] Tx 3G Phone Book Capability RSP (selected slot=0x%X, num of PB fields=%d)
[SIPC_1_PB] Tx 3G Phone Book Capability NTF (Selected slot=0x%X, Num of PB Fields=%d)
[SIPC_0_PB] Tx 3G Phone Book Capability NTF (Selected slot=0x%X, Num of PB Fields=%d)
[SIPC_1_PB] Rx Phone Book Access EXE (sipc msg len=%d, mode=0x%X, phonebook type=0x%X, index=%d)
[SIPC_0_PB] Rx Phone Book Access EXE (sipc msg len=%d, mode=0x%X, phonebook type=0x%X, index=%d)
[SIPC_1_PB] Invalid selected slot(=0x%X)
[SIPC_0_PB] Invalid selected slot(=0x%X)
[SIPC_1_PB] Invalid mode(=0x%X)
[SIPC_0_PB] Invalid mode(=0x%X)
[SIPC_1_PB] Invalid PB storage type(=0x%X)
[SIPC_0_PB] Invalid PB storage type(=0x%X)
[SIPC_1_PB] Phone Book Access was sent to stack
[SIPC_0_PB] Phone Book Access was sent to stack
[SIPC_1_PB] Rx Phone Book Access GET(Selected slot=0x%X, PB storage type=0x%X, Start Idx=%d, End Idx=%d)
[SIPC_0_PB] Rx Phone Book Access GET(Selected slot=0x%X, PB storage type=0x%X, Start Idx=%d, End Idx=%d)
[SIPC_1_PB] Invalid selected slot(=0x%X)
[SIPC_0_PB] Invalid selected slot(=0x%X)
[SIPC_1_PB] Invalid PB storage type(=0x%X)
[SIPC_0_PB] Invalid PB storage type(=0x%X)
[SIPC_1_PB] Invalid selected slot(=0x%X)
[SIPC_0_PB] Invalid selected slot(=0x%X)
[SIPC_1_PB] Invalid PB storage type(=0x%X)
[SIPC_0_PB] Invalid PB storage type(=0x%X)
[SIPC_1_PB] Invalid selected slot(=0x%X)
[SIPC_0_PB] Invalid selected slot(=0x%X)
[SIPC_1_PB] Invalid PB storage type(=0x%X)
[SIPC_0_PB] Invalid PB storage type(=0x%X)
[SIPC_1_PB] Invalid selected slot(=0x%X)
[SIPC_0_PB] Invalid selected slot(=0x%X)
[SIPC_1_PB] Invalid selected slot(=0x%X)
[SIPC_0_PB] Invalid selected slot(=0x%X)
[SIPC_1_PB] Invalid PB storage type(=0x%X)
[SIPC_0_PB] Invalid PB storage type(=0x%X)
[SIPC_1_PB] Invalid selected slot(=0x%X)
[SIPC_0_PB] Invalid selected slot(=0x%X)
