BoundGrr- Unable to register MsgId=%d
rrc_BoundGrr - Unable to de-register MessageId=%d
rrc_BoundGrr - RegistryTablePtr is NULL, MessageId=%d
GRR TID TABLE
ERROR: rrc_BoundGrr_RrToUrrcMsg MapExtMsgIdToIntMsgId failed for MsgId %d
GRR TID TABLE
rrc_BoundGrr_RrToUrrcMsg()-Unregistred %d Msg received
GRR TID TABLE
rrc_BoundGrr_RrToUrrcMsg()-Unregistred %d Msg received
GRR TID TABLE
Tx-URRC_GRR_ABORT_PRED_CONF_CNF, %d
Tx-URRC_GRR_CELL_CHANGE_TO_GSM, %d
Tx-URRC_GRR_CELL_CHANGE_TO_UTRAN_COMPLETE, %d
Tx-URRC_GRR_CELL_CHANGE_TO_UTRAN_FAILED, %d
Tx-URRC_GRR_CELL_RESELECTION_TO_GSM, %d
Tx-URRC_GRR_CELL_RESELECTION_TO_UTRAN_COMPLETE, %d
Tx-URRC_GRR_CELL_RESELECTION_TO_UTRAN_FAILED, %d
Tx-URRC_GRR_HANDOVER_TO_GSM, %d
Tx-URRC_GRR_HANDOVER_TO_UTRAN_COMPLETE, %d
Tx-URRC_GRR_HANDOVER_TO_UTRAN_FAILED, %d
Tx-URRC_GRR_INTER_RAT_HANDOVER_INFO_RSP, %d
Tx-URRC_GRR_READ_PRED_CONF_CNF, %d
Tx-URRC_GRR_CELL_RESELECTION_TO_GSM_STOP, %d
Tx-URRC_GRR_INTER_RAT_HANDOVER_INFO_REQ, %d
Tx-URRC_GRR-MESSAGE_UNKNOWN(%X), %d
Rx-GRR-MESSAGE_UNKNOWN(%X), %d
RX -Msg: [%s], TransactionId: [%d]
