RABM TID TABLE
ERROR: rrc_BoundURabm_URabmToUrrcMsg MapExtMsgIdToIntMsgId failed for MsgId %d
BoundRabm - All Tids removed by client %s
RABM TID TABLE
BoundRabm - Unable to remove all Tids by ClientInstId = %d
Rx-RABMAS-MESSAGE_UNKNOWN(%X), %d
RX -Msg: [%s], TransactionId: [%d]
RABM TID TABLE
Tx-RABMAS_RAB_INITIALISATION_IND, %d
Tx-RABMAS_RAB_ESTABLISH_IND, %d
Tx-RABMAS_RAB_ACTIVATE_IND, %d
Tx-RABMAS_RAB_RELEASE_IND, %d
Tx-RABMAS_RAB_MODIFY_IND, %d
Tx-RABMAS_RADIO_BEARER_RELEASE_IND, %d
Tx-RABMAS_RADIO_BEARER_ADDITION_IND, %d
Tx-RABMAS_SUSPEND_IND, %d
Tx-RABMAS_UMTSRATMODE_IND, %d
Tx-RABMAS_NONUMTSRATMODE_IND, %d
Tx-RABMAS-MESSAGE_UNKNOWN(%X), %d
