[rConfigBlkDedi] Get AsConfigDelivered %d
[rConfigBlkDedi] Set AsConfigDelivered %d
[rConfigBlkDedi] Clear AsConfigDelivered %d
[rConfigBlkDedi] Init AsConfigDelivered
[RRE] Get ReestCause %d
[RRE] Set ReestCause %d
[rConfigBlkDedi] Get ResumeCause %d
[rConfigBlkDedi] Set ResumeCause %d
[rConfigBlkDedi] Get ResumeTrigger %d
[rConfigBlkDedi] Set ResumeTrigger %d
[rConfigBlkDedi] Set isEstablishmentDone %d
[rConfigBlkDedi] Get isEstablishmentDone %d
[rConfigBlkDedi] Set isL2ConfigNeed %d
[rConfigBlkDedi] Get isL2ConfigNeed %d
[rConfigBlkDedi] Set GoingToIdleStart %d
[rConfigBlkDedi] Get GoingToIdleStart %d
[rConfigBlkDedi] Set ConnFallbackStart %d
[rConfigBlkDedi] Get ConnFallbackStart %d
[rConfigBlkDedi] Get IsNeedToResumeRB %d
[rConfigBlkDedi] Set isNeedToResumeRB %d
