NORMAL Initialisation of <GmmPduCodec>
Mbx: 0x%d


GmmDetachTypeIe -> %d
GmmCauseIe -> %d
IeLength %d exceeds mm_GmmIeValMaxLen[%d] %d.
IeLength %d exceeds mm_GmmIeValMaxLen[%d] %d.
FOPIe = %d
Length 0 of Mobile ID will be considered as invalid.
FOPIe = %d
GMM EDGE support flag = %d
GMM GPRS MS class = %d , GMM EGPRS MS class = %d
GMM PDU codec init, DTM_GPRS_MSC:%d DTM_EGPRS_MSC:%d SingleSlot:%d
SRVCC Support = %d
Is2GDisabled: %d and Is3GDisabled: %d
SRVCC Supported feature = %d, Srvcc Regi = %d
Need to display DCNR bit for NR !
GMM Ciphering Algorithm IE = %d
GMM Ciphering Algorithm IE is Not Present !
GMM Force To StandBy IE = %d
GMM Force To StandBy IE is Not Present
Optional IEs Include ->...
PTMSI Signature -> ...
Optional IEs Include ->...
Allocated PTMSI -> ...
Optional IEs Include ->...
Optional IEs Include ->...
Equivalent Plmn List -> ...
Optional IEs Include ->...
Optional IEs Include ->...
Optional IEs Include ->...
Optional IEs Include ->...
Optional IEs Include ->...

----------------------------------
Incorrect Base Address -> %02X
mm_NsUpdateCommonSignalingInfo MsgType = %d / PD = %d
HidePersonalInfo: Original Dump received is :
mm_NsUpdateCommonSignalingInfo TypeOfId = %d
mm_NsUpdateCommonSignalingInfo TypeOfId = %d
mm_NsUpdateCommonSignalingInfo TypeOfId = %d
Don't send UpdateCommonSignalingInfo for privacy MobilIdIndex = %d
HidePersonalInfo: Modified Dump is :
Don't need to send UpdateCommonSignalingInfo for privacy
No need update Isr Support bit
mm_UpdateGmmIeDatafromRegistry Update data from Registty
Registry Value of GEA2 Algorithm is:%d
Registry Value of GEA2 Algorithm is:%d
Registry Value of A5/4 Algorithm is:%d
Registry Value of A5/4 Algorithm is:%d
Registry Value of GEA4 Algorithm is:%d
Registry Value of GEA4 Algorithm is:%d
mm_SendGmmMessage send UNITDATA_REQ to LLC


GS31(GMM): ucTransactionID = 0x%02X, ucProtocol =%s, ucSendSeqNum =0x%02X
GS31(GMM): ucMessageType =0x%02X, ucChannel =0x%02X
GS31(GMM): Raw data length =%d


Received GMM_AUTH_AND_CIPH_REJ From Network..Contains No Mandatory or Optional IEs...[24.008]-9.4.11

Contains No Optional IEs.
Received GMM_RAU_REJECT From Network, 2 Mandatory IEs ->...[24.008]-9.4.17
Optional IEs Include ->...T3212 Value -> 0x%02X...
Received GMM_RAU_ACCEPT From Network...4 Mandatory IEs ->...[24.008]-9.4.15

2 Mandatory IEs ->...[24.008]-9.4.7
Received GMM_STATUS From Network... 1 Mandatory IE ->...[24.008]-9.4.18
Contains No Optional IEs.
Received GMM_INFORMATION From Network...No Mandatory IEs.
Received GMM_SERVICE_REJECT From Network...1 Mandatory IE ->...[24.008]-9.4.22
Contains No Optional IEs.
Received GMM_DETACH_REQUEST From Network...2 Mandatory IEs ->...[24.008]-9.4.5
Received GMM_SERVICE_ACCEPT From Networ...1 Mandatory IE ->...[24.008]-9.4.21
Received GMM_ATTACH_ACCEPT From Network 6 Mandatory IEs ->...Periodic RAU Update Timer Value -> %02X... SMS Radio Priority -> 0x%02X...
Received GMM_ATTACH_REJECT From Network...1 Mandatory IE ->...[24.008]-9.4.4
Received GMM_DETACH_ACCEPT From Network No Mandatory IEs ->...[24.008]-9.4.6..Contains No Optional IEs.

IMEI_SV ID Type Requested (1 = YES) -> %02X
Mandatory IE , IMEI_SV ID Type Requested NOT PRESENT !!!!.
Optional IEs Include ->...
RAND -> ...
Optional IEs Include ->...
GMM Cksn -> %02X
Optional IEs Include ->...
AUTN -> ...
Mobile Identity ->...
Mandatory IE , Mobile Identity NOT PRESENT !!!!.
RAU Update Result -> %02X (%s)...
Mandatory IE , RAU Update Result NOT PRESENT !!!!.
Periodic RAU Update Timer Value -> 0x%02X...
Mandatory IE , Periodic RAU Update Timer Value NOT PRESENT !!!!.
Optional IEs Include ->...
Mobile Identity ->...
Optional IEs Include ->...
List of N-PDU Numbers ->
Optional IEs Include ->...
Neogtiated Ready Timer Value -> %02X...
Optional IEs Include ->...
T3302 Timer Value -> %02X...
Optional IEs Include ->...
Cell Notification State -> %02X...
Optional IEs Include ->...
List of PDP Contexts -> ...
Allocated PTMSI -> ...
Mandatory IE , Allocated PTMSI NOT PRESENT !!!!.
Optional IEs Include ->...
PTMSI Signature -> ...
Detach Type -> 0x%02X... %s
Mandatory IE , Detach Type NOT PRESENT !!!!.
List of PDP Contexts -> ...
Mandatory IE , List of PDP Contexts NOT PRESENT !!!!.
RAI -> ...
Mandatory IE , RAI NOT PRESENT !!!!.
Optional IEs Include ->...
T3212 Value -> %02X...
PDP ACT ACCEPT from NW %d AddrInx =%d
Data 0x%x
PDP ACT REQ from NW %d AddrInx =%d
Data 0x%x
MOD REQ from NW %d AddrInx =%d
Data 0x%x
