NORMAL Initialisation of <GmmCellIndicationt>
GSM to UMTS Initialisation of <GmmCellIndicationt>
UMTS to GSM Initialisation of <GmmCellIndicationt>
Unknown Initialisation Type (%x) in mm_InitGmmCellIndication
UMTS Moved from No PS service to In PS serviec
UMTS Current and Sim RAI are same ChangeinRai : False
UMTS Current and Sim RAI are different ChangeinRai : TRUE
CnCommonNasInfo Absent !!!! PLMN Changed without LAC changing?! Msg ignored in mm_UpdateAndProcessGmmCellData
SIB derived CN information does not include PS domain specific SI (i.e. RAC and network mode)...assuming PS domain currently unavailable in selected cell
Network sourced CN information does not include PS domain specific SI (i.e. RAC and network mode)...assuming PS domain currently unavailable in selected cell
PLMN identity not included - using previously stored value
CN Common SI (LAC) not included - using previously stored value
SIB derived CN information does not include CN common GSM-MAP NAS SI (i.e. LAC)...
PLMN identity not included - using previously stored value
CN Common SI (LAC) not included - using previously stored value
Setting GMM_RAI_CHANGED_FLG_...
URRC_MM_NO_CELL_IND....
Moved from PS no service to PS in Service
GSM Current and Sim RAI are same ChangeinRai : False
GSM Current and Sim RAI are different ChangeinRai : TRUE
mm_GmmCellData.CellChange is set to FALSE.
mm_GmmCellData.CellChange is set to TRUE.
NwExtUtbf= %d
EncodedSizeinBits -> %d
Access Technology changed...
Access Technology did not change...
CR 98 :Set : mm_SetGmmFlag....
CR 98 :Clear : mm_SetGmmFlag....
....cell does not support PS.
....ignored as DataResumption == GRR_GMM_NO_RESUMPTION.
GRR_MM_NO_CELL_IND....
Because of Power off detach or PS detach PS off and GMM Deregistered we skip GmmCellData process.
ERROR: unknown TypMsg 0x%02X in MM_UMTS_RAT_MODE
ERROR: unknown TypMsg 0x%X in MM_GSM_RAT_MODE
discard GMM SM EST REQ
SameRrConnexFailAction = %d, ProcessCellInfo =%d
Current serving cell is not supportting PS services(or barred), GMM_GPRS_ATTACH_FLG = FALSE
LAI is not changed, so send Registration ind to NS for PS barred status
NO CELL IND, keep GMM_GPRS_ATTACH_FLG == TRUE
Current serving cell is supporting PS services and UE GMM REG/UPDATED, GMM_GPRS_ATTACH_FLG = TRUE
Send reg status ind(PS not supported -> supported) on recovery to prev reg RAI
GMM shall process new cell details now...
GMM shall process new Unit Data Ind details now...
NMO-1 GMM shall process new cell details now. Received GSM CELL IND ..
GMM shall not process new cell details now...shall process on completion of MM location updating procedure
GMM shall not process new cell details...CSFB call about to initiated
In MM_WAIT_FOR_RR_CON_LOC_UPD state LAI changed, After Cell indication LAU should be initiated..GMM shall not process new cell details now till Perform LAU procedure
GMM shall not process new cell details...URRC_MM_CELL_IND received in while a PS signalling connection exists
GMM shall process new cell details now...
GMM processing of new cell details in %s in mm_ProcessGmmCellInformation
Attempting to go back to GMM State before Supension...mm_GmmStateBeforeSuspension = %s
Abort any ongoing GMM procedure and later Trigger GPRS detach procedure in GMM state= %s
GMM state was GMM_SERVICE_REQUEST_INITIATED but have moved to GSM RAT, reverting to GMM_REGISTERED
ERROR: Invalid mm_GmmState....
CLEARING Gmm Regist status Cause
NOT CLEARING Gmm Regist status Cause, Cause %d
GMM_NO_IMSI -> Should Never Have Got Here !!!
ERROR: Unexpected mm_GmmServiceState....
GPRS attach (re)initiation...
RAI Changed
Cell Changed & Must Retry in New Cell
GMM_T3302 had expired while GMM was suspended
Cell changed and Att req action is GMM_NO_ATT_ACTION under attemping to attach / dereg state, need to do attach again.
Need to do GPRS Attach UE is in NMO1 So try Combined Attach to establish the Gs association in the MSC/VLR.
GMM is in LIMITED and PS domain barred... So nothing done here...
CS call had been attempted, retry now...
Change of Cell into New Routing Area....
New RAI before Est Cnf has been received. Must Break RR Con and start Again. Please Wait...
GPRS Attach Procedure Following Intersystem Change Between Cells Belonging to the Same RA....
Change of cell within the same RA => Perform Cell Update [24.008]-4.7.3.1.5.e....
Access barred Due to Access Class Control....
Must Break RR Con. .
Lower Layer Failure....
Loss of coverage during Signalling, end the signalling
GMM_REGISTERED.mm_GmmCellData.NetworkService = %d
ISR is activated but RAI is changed after L2U Rat Change. RRC Est Cause is set to InterRAT Cell Reselection.
RAU recovery procedure is performed..
change of cell into new routing area....
change of cell in same routing area having received cause 'Retry upon entry into a new cell'....
GMM CELL DATA RAI != SIM RAI and No timer for retrying RAU, Here RAU is necessary.
RAU procedure as GMM_T3302 expired in GMM_SUSPENDED state...
RAU procedure should be triggered due to NMO change (not periodic)
change of cell into new routing area....
RAU needed flag is set
access no longer barred....
Change of Cell into New Routing Area....
Network mode change during GPRS detach procedure for CS services
IMSI Detach Procedure After RAU Procedure Following Intersystem Change Between Cells Belonging to the Same RA....
Change of Cell in Same Routing Area....
Lower Layer Failure....
MO/MT Call was attempted in NMO1. This should be stopped before RAU Procedure ....
RAU will be pended while MO/MT call is in progress....
Initiating RAU Procedure .... after WFRAU timer is expired
Initiating RAU Procedure .... if Quick Rollback is over
Initiating RAU Procedure ....
RAU procedure not initiated due to access class barred....
SM Informed of 'Lost' Radio Coverage....
SM Informed of Regained Radio Coverage....
SM Informed of 'Lost' Radio Coverage....
SM Informed of Regained Radio Coverage....
Resumed Again on UMTS Rat So no need to Do Anything
CS call had been attempted, retry now...
CS call had been attempted, retry now...
ERROR: mm_GmmState and mm_GmmServiceState incompatible!
Change of Cell into New Routing Area. Starting RAU...
New RAI before Est Cnf has been received. Must Break RR Con and start Again. Please Wait...
RAT Change Detected During RAU Procedure...RAU Procedure Following Intersystem Change Between Cells Belonging to the Same RA
Change of Cell in Same Routing Area....
Access Barred Due to Access Class Control....
Must Break RR Con. .
Gmm cell data. network service exceeds the limit
SM informed of 'Lost' Radio Coverage....
Change of Cell into New Routing Area....
Change of RAC Detected, during Detach for PS Switching
New RAI before Est Cnf has been received. Must Break RR Con and start Again. Please Wait...
RAT Change Detected During Detach -> RAU Procedure then Normal GPRS Detach Following Intersystem Change Between Cells Belonging to the Same RA....
change of cell within the same RA....
.... lower layer failure
Change of cell into new RA...
RRC requested to 'release' PS signalling connection before RAU procedure initiation...
PMM_CONNECTED: RRC requested to 'release' PS signalling connection before RAU procedure initiation...%d
RAU procedure 'interupts' service request procedure...
CS call had been attempted, retry now...
Loss of coverage during service request procedure...
mm_GmmCellIndDb[MmStackId].mm_GmmCellData.NetworkService exceeds the limit
SM informed of 'lost' radio coverage....
RRC requested to 'release' PS signalling connection Because Lost Coverage Before Moving to Conn Mode
GCF Mode is Enabled
In UMTS RAT, PMM connected Mode and Network mode 1
Current and SIM data PLMNs are not same and PLMN Found in Equivalent Plmn List
LA and RA of the SIM and the current cell data are same.
GRR_GMM_SUSPEND_IND received in state %s
mm_EncodedDrxParam = 0x%02X 0x%02X
Invalid NewState in mm_SetGmmStateBeforeSuspension
Re-setting GMM CellData
Setting GMM CellData for Recovery
Restore Gmm CellData for Recovery
GMM Cell Data RAC -> 0x%02X
mm_GmmCellData.Rai = %02X %02X %02X %02X %02X %02X
mm_GmmCellData.NetworkMode = %s
---------------------Current GMM cell details---------------------
RAT mode -> %s
Access tech type -> %s
RAT mode -> %s, Network service -> %s
Forbidden PLMN
Forbidden PLMN for GPRS services
Forbidden LA
Forbidden LA for roaming
PLMN selection has been started by MM
Network access -> %s, Network mode -> %s
RAI -> %02X %02X %02X %02X %02X %02X, Cell identity -> %07X
Cell change -> %s, Data resumption -> %s
Cell change -> %s
---------------------Previous GMM cell details---------------------
RAT mode -> %s, Network mode -> %s
Access tech type -> %s
RAI -> %02X %02X %02X %02X %02X %02X, Cell identity -> %07X
Even though Band is changed in NMO1, we don't have anything to send again!
Wrong Action =%d
RAU recovery procedure is performed..
RAT Change to UMTS Detected -> GSM to UMTS Intersystem Change Between Cells Belonging to Same RA...GPRS Functional State was %s on Intersystem Change....
=> Initiate RAU Procedure Immediately....
Normal RAU Procedure on Intersystem Handover from GSM to UMTS during CS Connection....
RAU Procedure Not Required Until Uplink Signalling or Data Transmission. [24.008]-4.7.1.7 (b)...
RAT Change to GSM Failed, Now Back in UMTS again -> MS in Same Access Network as when last sent user data or signalling, normal procedures shall be followed.....
mm_RauForGprsResumeReEntryFlag is RESET as RauNeeded is Set....
RAU Procedure Initiation Required for GPRS Resumption in the Network....DataResumption=%d, mm_RauForGprsResumeReEntryFlag=%d
RAU Procedure Initiation as GMM_T3302 Expired in GMM_SUSPENDED state....
RAU recovery procedure is performed..
Cell update procedure will be blocked during Manual PLMN searching.
Change of Cell in Same Routing Area....
RAT Change to GSM Detected -> UMTS to GSM Intersystem Change Between Cells Belonging to Same RA....PMM functional state was %s on intersystem change....
=> Initiate RAU Procedure Immediately....
RAU procedure not required until uplink signalling or data transmission. [24.008]-4.7.1.7 (b)...
=> Initiate RAU Procedure due to MM_AUTO_PLACEMENT_IN_QUEUE....
RAT Change to UMTS Failed, Now Back in GSM again -> MS in same access network as when last sent user data or signalling, normal procedures shall be followed.....
