%s in mm_DecodeTmsiReallocationMsg
Mesasge received in Incorrect State
Received New TMSI in TMSI Re-Allocation Command
Old TMSI ->...
New TMSI ->...
Received New IMSI in TMSI Re-Allocation Command, Deleting TMSI ....
Received Neither TMSI nor IMSI in TMSI Re-Allocation Command. Ignoring Message, Sending Status Msg to Network
Inform RR(C) of New TMSI...
