[PROC][CA] ERROR: NumofScell(%d)
[PROC][CA] CaScellInfo: NumofScell(%d)/ScellIndex(%d)/CcIndex(%d)/ArrayIndex(%d)/CcIdxBitMap(0x%X)/UlCcIdxBitMap(0x%X)/ScellIndex_CC0(%d), m_CommonCfg.PcellCc(%d), band(%d), scellIdx(%d)
(I)Skip DB update: m_CcIdx(%d) MyScellIndex(%d)
(I)Skip DB update: MyScellIndex(%d) MyArrayIndex(%d)
[PROC][CA] n(%d)/k(%d)/current(%d)/target(%d)/act_cnt(%d)/isAbove6GHz(%d)/ca_state(%d), scs(%d)
[NR IPC] L1C_PHY_CELLGROUP_SCELL_CONFIG_CNF, BM_SrcCcForCnfMsg(%d), demod_cc(%d) Cmd(%d)
[NR IPC] L2_PHY_SCELL_INFO_IND, BM_SrcCcForCnfMsg(%d)
[NR IPC] L2_PHY_SCELL_DEACT_IND , BM_SrcCc/StackId(%d/%d) m_CcIdx(%d) ServingCellId(%d)
(F)Error in SendScellDeactInd: m_CcIdx(%d)
(F)ERROR in Update_CaCommonConfigInfo: state(%d)
(F)ERROR in Update_CaDlConfigInfo: state(%d)
[NR_CA_PROC] Set NR_DC_CCH_RECONFIG_DCI_LENG: status_reg(%d)
(F)ERROR in Update_CaUlConfigInfo: state(%d)
(F)Check in Update_CaScellFreqDlInfo: NumOfScell(%d)
(DEBUG) NumOfScell(%d)/Index(%d)/IsConditionTrue(%d)/present_flag(0x%X/0x%X/0x%X/0x%X)
(F)Check in Update_CaScellFreqDlInfo: scellIndex(%d) NumOfScsSpecificCarrier(%d)
(F)Error in NumOfScsSpecificCarrierList(%d)
PhyCellGroupCfg: ScellIdxToArrayIdx (%d)(%d) (%d)(%d) (%d)(%d) (%d)(%d)
PhyCellGroupCfg: carrierBandwidth(%d)(%d) subcarrierSpacing(%d)(%d) NumOfScsSpecificCarrier (%d)(%d)
(F)ERROR in Cmd(%d)
(F)ERROR in ActCcIdx(%d)
(F)ERROR in NumOfTotalDlActCC(%d)
(F)ERROR in Cmd(%d)
Update_CaDlActDeactInfo: Cmd(%d), NumOfTotalDlActCC(%d) ActCcIdx(%d) Valid(%d)/isAbove6GHz(%d)
Error in Update_SCellConfig: sCellIndex(%d)
Error in Update_SCellConfig: ArrayIndex(%d)
Error in Update_SCellConfig: sCellIndex(%d)/ArrayIndex(%d)/sCellIndex_inSHM(%d)
(F)Error in Update_ScellStatus: m_CcIdx(%d)
(F)Error in Update_ScellStatus: Cmd(%d)
PHY_PHY_SCELL_STATUS_UPDATE_IND m_CcIdx(%d), ActDeact(%d), NrActFlag(0x%x) Ssb_Detected_Scs(%d), isAbove6GHz(%d)
[NR IPC] PHY_PHY_SCELL_STATUS_UPDATE_IND, BM_SrcCc(0x%X), BM_DstCc(0x%X)
(F)Error in Config: m_CcOffsetIdx(%d)
[NR IPC] L1C_PHY_SCELL_ACTDEACT_CNF (ACT), BM_SrcCcForCnfMsg(%d), ipc(%d)
[NR IPC] L1C_PHY_SCELL_ACTDEACT_CNF (DEACT), BM_SrcCcForCnfMsg(%d), ipc(%d)
(I) Check State: %d
[PROC][CA] CaCfgState(%d), ccidx(%d), event(%d)
(F)ERROR in Control_CaCfgState: state(%d)
(F)ERROR in CaActDeActState: state(%d)
(I)Skip State Chage: m_CcIdx(%d) MyScellIndex(%d)
(F)Error in Set_ScellDeactTimerTarget: timer(%d)
Set_ScellDeactTimerTarget: timer(%d)
(F)Error in Set_NrCaStatusInSharedData: CaInfoType(%d)
