Error in isr_type(%d)
[DCCCH]NrCellGroupCommonCfgUpdateDcCfg HARQ_ACK_codebook(%d)
[DCCCH]NrCellGroupCommonCfgUpdateDcCfg ps_Offset(%d), sizeDCI_2_6(%d), ps_PositionDCI_2_6(%d), ps_WakeUp(%d)
NrCellGroupCommonCfgUpdateShmForScell: valid(%d)/value(%d)
[PROC][CELLGROUP] present_flag: total/reconfigwithsync/common/dedi (0x%X)(0x%X)(0x%X)(0x%X)
[NrCellGroupPcellCfgUpdateDcCfg] DCCCH, reportTriggerSize:%d
[NrCellGroupPcellCfgUpdateDcCfg] codeBlockGroupFlushIndicator : %d
[Cell level RMP] dedi(%d), idx,num(%02d), id(%d), Bitmaps: %d slot(0x%x), periodIdx,Val(%d,%d), patternH,L(0x%x,0x%x), scs(%d)
[Cell level RMP] dedi(%d), idx,num(%02d), id(%d) Coreset: %d, scs(%d)
[TBS_LBRM][RRC_configured] NR_ServingCellConfig_initialDownlinkBWP(%d), NR_BwDownlink_bwp_Dedicated(%d), NR_BWPDownlinkDedi_pdsch_Config(%d), NR_MCFG_IE_CONFIG_FLAG(%d)
[NrCellGroupPcellCfgUpdateSpCfg] pusch_ServingCellConfig_flag(%d), maxMIMO-Layer:%d, cbgti(%d)
[HBF][Beamlock][fromRRC] p_CellGroupPcellConfigDedicated->present_flag (0x%08x), ue_BeamLockFunction (0x%x), p_CellGroupPcellConfigDedicated->ue_BeamLockFunction (0x%x), NrCsiBmCmmCfg.ueBeamLock_enable (%d)
PhyCellGroupCfg: carrierBandwidth(%d)(%d) subcarrierSpacing(%d)(%d) NumOfScsSpecificCarrier (%d)(%d)
[PROC][CELL_GROUP] INTRA_TO_BWP: present_flag(0x%X)/(0x%X)/(0x%X)/(0x%X)/(0x%X) xcarrier(0x%X/%d/%d)
[NR_CELL_GROUP_CFG_PROC] Wrong dmrs_TypeA_Position value ~!
[PHYPROC][CELLGROUP] Do not copy SCELL config (Cc/Scell/Array/mCc)(%d/%d/%d/%d)
[PHYPROC][BWP] Cmd(%d), NumofScell(%d), ccIndex(%d), sCellIndex(%d), arrayIndex(%d)
[PHYPROC][CELLGROUP] (I)Do not handle IPC: Cmd(%d)
(F)ERROR in NrCellGroupScellCfgUpdateDcCfg: sCellIndex(%d)(%d)
(F)ERROR in NrCellGroupScellCfgUpdatePdschCfg: sCellIndex(%d)(%d)
[RMP LTE-CRS] scellIdx(%d), dedi(%d), present_flag(0x%x), carrierFreqDL(%d), carrierBandwidthDL(%d), nrofCRS-Ports(%d), v-shift(%d), numOfMbsfnSubframeConfig(%d)
[RMP LTE-CRS] mbsfnSubframeConfig[%d]: present_flag(0x%x), period(%d), offset(%d), alloc1(%d,0x%x), alloc2(%d,0x%x)
[Cell level RMP][PDSCH_DEV] scellIdx/dedi(%d), idx,num(%02d), id(%d), Bitmaps: %d slot(0x%x), periodIdx,Val(%d,%d), patternH,L(0x%x,0x%x), scs(%d)
[Cell level RMP][PDSCH_DEV] scellIdx/dedi(%d), idx,num(%02d), id(%d) Coreset: %d, scs(%d)
PhyCellGroupCfg in SIB: carrierBandwidth(%d)(%d) subcarrierSpacing(%d)(%d) NumOfScsSpecificCarrier (%d)(%d)
