[Proc Rxmode] Ignore REQ IPC curRxmode(%d) nextRxmode(%d)
[Proc Rxmode] Configure: Rx ant num(%d)
[Proc Rxmode] NrRxmodeChangeTxCfg indFlag(%d) RxMode(%d)
[NR IPC][Proc Rxmode] L1C_PHY_RXMODE_CHANGE_IND, BM_SrcCcForCnfMsg(%d), ind_Rxpath(%d), dataInactivity_Flag(%d), ulInd(%d)
[NR IPC][Proc Rxmode] L1C_PHY_RXMODE_CHANGE_CNF, BM_SrcCcForCnfMsg(%d), demod_cc(%d)
[Proc Rxmode][VoNR] num_layer(%d) Dlgrant_Ratio(%d) highRankMarginTimer(%d) next_rxmode(%d) Trs_flag(%d) valid_Sinr(%d) pdschBler(%d)
[Proc Rxmode][DI] dataInactivestatus On Current Rxmode(%x),Rx0_Sinr_ssb(%d),Rx0_Sinr_trs(%d),trsValid(%d), trs_sinr_valid(%d), DlgrantRatio(%d), DLbler(%d), ditimer(%d), Timer_dataInact(%d), CdrxTimer(%d)
[Proc Rxmode][DA] num_layer(%d) Dlgrant_Ratio(%d) curCRC(%d) crcSkipTimer(%d) crcAckCnt(%d) blerCnt(%d) CQI(%d) SINR(%d) DlBler(%d) next_rxmode(%d)
[Proc Rxmode][VoNR] VoNrStatus(%d)
[Proc Rxmode][SCELL] m_CcIdx(%d) PcellCc(%d) next_rxmode(%d)
[Proc Rxmode] Operate: PHY_L1C_RXMODE_CHANGE_REQ Rxmode(0x%x) Pos(%d)
[Proc Rxmode] Rxmode Possible 4rx PHY_L1C_MIB_ACQ_REQ (%d) rxmode_bitmap(%d) isAbove6GHz(%d)
[Proc Rxmode] Rxmode Possible 4rx PHY_L1C_DRX_WAKEUP_INIT_REQ (%d) rxmode_bitmap(%d) isAbove6GHz(%d)
[Proc Rxmode] SysParam End rxmode_bitmap Mismatch!!! cur_rxmode(%d), Config_rxmode(%d)
[Proc Rxmode] Rxmode Possible 4rx PHY_L1C_SYS_PARAM_CHANGE_REQ Pos(%d) NTM_MODE(%d) rxmode_bitmap(%d)
[Proc Rxmode] SysParam Cnf done MtmCheck(%d) sysparamCfg_eventInfo(%d)
[Proc Rxmode] PHY_L1C_TMU_CTRL_IND controlOn(%d) RI(%d)
