Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Unsupported protocol version - R8~R11 supported
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Unsupported protocol version - R8~R11 supported
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Unsupported protocol version - R8~R11 supported
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Unsupported protocol version - R8 ~R11 supported
rrc_iePhDlSecondaryCellInfo_getDlScramblingCode: Asn_DL_SecondaryCellInfoFDD_continue_chosen
rrc_iePhDlSecondaryCellInfo_getDlScramblingCode: Asn_DL_SecondaryCellInfoFDD_continue_chosen
rrc_iePhDlSecondaryCellInfo_getDlScramblingCode: Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Unsupported protocol version - R8~R11 supported
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Unsupported protocol version - R8~R11 supported
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Unsupported protocol version - R8~R11 supported
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Unsupported protocol version - R8~R11 supported
Unsupported protocol version - R8~R11 supported
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Asn_DL_SecondaryCellInfoFDD_continue_chosen
Unsupported protocol version
dlSecondaryCellConfigStatus = %d of cell %d
Is64QamConf = %d of cell %d
hs_DSCH_TBSizeTable = %d dlScramblingCode = %d of cell %d
measurementPowerOffset = %d of cell %d
uarfcn_DL = %d of cell %d
differentTxModeFromServingHS_DSCHCell = %d of cell %d
[SUCCESS] DlSecondaryCellInfo IE, primaryCPICH_Info[%d]
[FAILURE] DlSecondaryCellInfo IE, primaryCPICH_Info[%d]
