RrmProcSmHdlrError::RRM_L1C_DRX_AVAILABLE_IND_ErrorHandler
RrmProcSmHdlrError::RRM_L1C_DRX_SLEEP_STATE_IND_ErrorHandler CdrxState:(enum)%d
>>DRX PBD is running now. Exceptional Message flow detected
>>DRX PBD is already terminated
>> Not normal terminated, Disable related flags
RrmProcSmHdlrError::RRM_L1C_CGI_HOLD_IND_ErrorHandler
RrmProcSmHdlrError::RRM_L1C_CGI_MEAS_SCHEDULE_IND_ErrorHandler
RrmProcSmHdlrError::RRM_L1C_CGI_START_CNF_ErrorHandler
RrmProcSmHdlrError::RRM_L1C_CGI_STOP_CNF_ErrorHandler
RrmNrProcSvHdlrError::RRM_RRC_BCH_CONFIG_REQ_ErrorHandler
RrmNrProcSvHdlrError::RRM_RRC_BCH_RELEASE_REQ_ErrorHandler
RrmNrProcSvHdlrError::RRM_RRC_CGI_START_REQ_ErrorHandler
RrmNrProcSvHdlrError::RRM_RRC_CGI_STOP_REQ_ErrorHandler
RrmNrProcSvHdlrError::RRM_RRC_FEDV_STATE_IND_ErrorHandler
RrmNrProcSvHdlrError::RRM_RRC_FREQ_SCAN_REQ_ErrorHandler
RrmNrProcSvHdlrError::RRM_RRM_HOLD_IND_ErrorHandler
RrmNrProcSvHdlrError::RRM_RRC_RAT_RESUME_REQ_ErrorHandler
RrmProcSmHdlrError::RRM_RRC_RAT_SUSPEND_REQ_ErrorHandler
RrmNrProcSvHdlrError::RRM_RRM_RAT_RESUME_REQ_ErrorHandler
RrmProcSmHdlrError::RRM_RRM_RAT_SUSPEND_REQ_ErrorHandler
RrmProcSmHdlrError::RRM_RRM_RESTART_IND_ErrorHandler
RrmProcSmHdlrError::RRM_RRM_RETURN_TO_PREV_SERVCELL_IND_ErrorHandler
RrmProcSmHdlrError::RRM_L1C_GAP_CONFIG_CNF_ErrorHandler
RrmProcSmHdlrError::RRM_RRC_MODEM_STOP_REQ_ErrorHandler
RrmProcSmHdlrError::RRM_L1C_POS_MEAS_CONFIG_CNF_ErrorHandler
RrmProcSmHdlrError::RRM_L1C_POS_MEAS_RESULT_IND_ErrorHandler
RrmProcSmHdlrError::RRM_RRC_POS_MEAS_CONFIG_REQ_ErrorHandler
RrmProcSmHdlrError::RRM_RRC_POS_MEAS_RESULT_IND_ErrorHandler
RrmProcSmHdlrError::RRM_RRC_POS_MEAS_ABORT_IND_ErrorHandler
