====CP crash detected! ExcptionCode:0x%X====
Invalid ABOX-VSS corss DM argNum=%d
[VHM_CROSS_LOG][ID=%d][P1:0x%X][P2:0x%X] WDMA4_BUFFER_FULL
[VHM_CROSS_LOG][ID=%d][P1:0x%X][P2:0x%X] TXSE ST
[VHM_CROSS_LOG][ID=%d][P1:0x%X][fwTime:%d] VSSIF(TA:%d)
[VHM_CROSS_LOG][ID=%d][P1:0x%X][P2:0x%X] TXSE_close
[VHM_CROSS_LOG][ID=%d][P1:0x%X][P2:0x%X] VOICE_BUFFER_FULL
[VHM_CROSS_LOG][ID=%d][P1:0x%X][P2:0x%X] RXSE(TA:%d)
[VHM_CROSS_LOG][ID=%d][P1:0x%X][P2:0x%X] SW_MIXER
[VHM_CROSS_LOG][ID=%d][P1:0x%X][P2:0x%X] RDMA3_BUFFER_EMPTY
[VHM_CROSS_LOG][ID=%d][P1:0x%X][P2:0x%X] ABOX CLK CHANGED
[VHM_CROSS_LOG][ID=%d][P1:0x%X][P2:0x%X] MIF CHANGED
[VHM_CROSS_LOG][ID=%d][P1:0x%X][P2:0x%X] BUSC CHANGED
[VHM_CROSS_LOG][ID=%d][P1:0x%X][P2:0x%X]
